KEEPER31337/Homepage-Back-R2

.github/PULL_REQUEST_TEMPLATE.md

close: #1
- PR 템플릿을 작성하였습니다.
화이팅 🔥

docs: PR Template 생성

---

src/main/java/com/keeper/homepage/global/error/BusinessException.java
src/main/java/com/keeper/homepage/global/error/ErrorCode.java
src/main/java/com/keeper/homepage/global/error/ErrorResponse.java
src/main/java/com/keeper/homepage/global/error/ExceptionAdvice.java

close: #18
`global exception advice` 제작
`ErrorCode`로 모든 코드 관리
`ErrorResponse`로 응답 포맷 정형화
`BusinessException` class로 모든 비즈니스 예외 처리
화이팅입니다..!

공통 exception 처리 코드 작성

---

src/main/java/com/keeper/homepage/domain/attendance/dao/AttendanceRepository.java
src/main/java/com/keeper/homepage/domain/attendance/entity/Attendance.java
src/main/java/com/keeper/homepage/domain/member/dao/MemberRepository.java
src/main/java/com/keeper/homepage/domain/member/entity/Member.java
src/test/java/com/keeper/homepage/IntegrationTest.java
src/test/java/com/keeper/homepage/domain/attendance/AttendanceTestHelper.java
src/test/java/com/keeper/homepage/domain/attendance/dao/AttendanceRepositoryTest.java
src/test/java/com/keeper/homepage/domain/member/MemberTestHelper.java
src/test/java/com/keeper/homepage/domain/member/dao/MemberRepositoryTest.java

close: #13 
attendance entity repository 생성
과거 코드 보면서 오열중...

#13 attendance entity repository 생성

---

src/test/java/com/keeper/homepage/global/util/file/FileServerUtilTest.java
src/test/java/com/keeper/homepage/global/util/thumbnail/server/ThumbnailServerPathGeneratorTest.java

close: #47
테스트 코드에서 구분자로 인한 에러를 해결하였습니다.
`feature/` 사용하는 것을 까먹었네요..
앞으로 주의하겠습니다..

test: `File.separator`를 사용하여 구분자 수정

---

src/test/java/com/keeper/homepage/domain/attendance/AttendanceTestHelper.java
src/test/java/com/keeper/homepage/domain/attendance/dao/AttendanceRepositoryTest.java
src/test/java/com/keeper/homepage/domain/member/MemberTestHelper.java
src/test/java/com/keeper/homepage/domain/member/dao/MemberRepositoryTest.java

close: #44
수행한 작업을 설명해주세요.
_뇌 빼고 코딩하기_
드르렁 푸우 드르렁 푸우

Feature/#44 member test helper에 generate() 메서드 추가

---

src/main/java/com/keeper/homepage/domain/member/dao/friend/FriendRepository.java
src/main/java/com/keeper/homepage/domain/member/entity/Member.java
src/main/java/com/keeper/homepage/domain/member/entity/friend/Friend.java
src/test/java/com/keeper/homepage/IntegrationTest.java
src/test/java/com/keeper/homepage/domain/member/dao/friend/FriendRepositoryTest.java

close: #38 
Friend Entity, Repository 생성하였습니다!
후딱 만들어봤습니다 😀

feat: Friend Entity, Repository 생성 #38

---

src/docs/auth/auth.adoc
src/main/java/com/keeper/homepage/domain/auth/api/SignUpController.java
src/main/java/com/keeper/homepage/domain/auth/application/CheckDuplicateService.java
src/main/java/com/keeper/homepage/domain/auth/application/SignUpService.java
src/main/java/com/keeper/homepage/domain/auth/dto/request/SignUpRequest.java
src/main/java/com/keeper/homepage/domain/auth/dto/response/CheckDuplicateResponse.java
src/main/java/com/keeper/homepage/domain/member/dao/MemberRepository.java
src/main/java/com/keeper/homepage/domain/member/entity/Member.java
src/main/java/com/keeper/homepage/domain/member/entity/embedded/Generation.java
src/main/java/com/keeper/homepage/domain/member/entity/embedded/Profile.java
src/main/java/com/keeper/homepage/global/config/password/PasswordConfiguration.java
src/main/java/com/keeper/homepage/global/config/security/SecurityConfiguration.java
src/main/java/com/keeper/homepage/global/error/ErrorCode.java
src/main/java/com/keeper/homepage/global/error/ExceptionAdvice.java
src/test/java/com/keeper/homepage/IntegrationTest.java
src/test/java/com/keeper/homepage/domain/auth/api/SignUpControllerTest.java
src/test/java/com/keeper/homepage/domain/auth/application/CheckDuplicateServiceTest.java
src/test/java/com/keeper/homepage/domain/auth/application/SignUpServiceTest.java
src/test/java/com/keeper/homepage/domain/member/MemberTestHelper.java
src/test/java/com/keeper/homepage/domain/member/dao/MemberRepositoryTest.java

close: #32
중복체크 API 3개 추가
81221295a5e091d3126d4c0b5738b388148e08fc 이 커밋 하나만 보시면 됩니다!
👀👀👀👀👀👀👀👀👀

Feature/#32 이메일 로그인 학번 중복체크기능 구현

---

src/test/java/com/keeper/homepage/domain/clerk/seminar/dao/SeminarRepositoryTest.java

N/A
test 코드에서 2번 save하는 코드를 수정하였습니다..
나는 바보 멍청이..

test: 2번 세이브 되는 코드 수정

---

src/main/java/com/keeper/homepage/domain/seminar/dto/request/SeminarStartRequest.java
src/main/java/com/keeper/homepage/global/error/ExceptionAdvice.java
src/test/java/com/keeper/homepage/domain/seminar/api/SeminarControllerTest.java

close: #126
벌벌 떨면서 merge 눌렀는데 충돌도 없었고 코드도 다 반영되어 있네요..!
이용 가능한 세미나 조회 테스트 코드에 **권한 정보** 넣어주는 기능만 추가했습니다! https://github.com/KEEPER31337/Homepage-Back-R2/pull/127/commits/1fb1702710b6bb2e039d72754732d1a5a97bdd1e
https://github.com/KEEPER31337/Homepage-Back-R2/pull/119#discussion_r1111889030 이 부분은 오늘 회의 때 말씀드려보겠습니다!
오늘부터 진짜 세미나 출석 구현... 시작....

Feature/merge한 코드들 수정 및 점검

---

src/docs/asciidoc/seminar/seminar-attendance.adoc
src/docs/asciidoc/seminar/seminar.adoc
src/main/java/com/keeper/homepage/domain/seminar/api/SeminarAttendanceController.java
src/main/java/com/keeper/homepage/domain/seminar/api/SeminarController.java
src/main/java/com/keeper/homepage/domain/seminar/application/SeminarAttendanceService.java
src/main/java/com/keeper/homepage/domain/seminar/application/SeminarService.java
src/main/java/com/keeper/homepage/domain/seminar/application/convenience/ValidSeminarFindService.java
src/main/java/com/keeper/homepage/domain/seminar/dao/SeminarAttendanceRepository.java
src/main/java/com/keeper/homepage/domain/seminar/dao/SeminarRepository.java
src/main/java/com/keeper/homepage/domain/seminar/dto/request/SeminarAttendanceRequest.java
src/main/java/com/keeper/homepage/domain/seminar/dto/response/SeminarAttendanceResponse.java
src/main/java/com/keeper/homepage/domain/seminar/dto/response/SeminarResponse.java
src/main/java/com/keeper/homepage/domain/seminar/entity/Seminar.java
src/main/java/com/keeper/homepage/domain/seminar/entity/SeminarAttendance.java
src/main/java/com/keeper/homepage/global/error/ErrorCode.java
src/test/java/com/keeper/homepage/domain/seminar/api/SeminarApiTestHelper.java
src/test/java/com/keeper/homepage/domain/seminar/api/SeminarAttendanceControllerTest.java
src/test/java/com/keeper/homepage/domain/seminar/api/SeminarControllerTest.java
src/test/java/com/keeper/homepage/domain/seminar/dao/SeminarAttendanceRepositoryTest.java
src/test/java/com/keeper/homepage/global/restdocs/RestDocsHelper.java

close: #85
세미나 출석 기능을 구현했습니다..!
https://github.com/KEEPER31337/Homepage-Back-R2/pull/128/commits/fcabd43a9d031efa5a141ebaaab7ccdbbc02db85 커밋 관련 자료입니다. - https://jojoldu.tistory.com/516
세미나 API 끝이 보이네요..?
rest docs에서 사용할 수 있는 Enum 관련 편의 메서드도 만들어 보겠습니다. https://github.com/KEEPER31337/Homepage-Back-R2/issues/117

Feature/세미나 출석 기능 구현

---

src/docs/asciidoc/seminar/seminar-attendance.adoc
src/main/java/com/keeper/homepage/domain/seminar/api/SeminarAttendanceController.java
src/main/java/com/keeper/homepage/domain/seminar/application/SeminarAttendanceService.java
src/main/java/com/keeper/homepage/domain/seminar/dao/SeminarAttendanceRepository.java
src/main/java/com/keeper/homepage/domain/seminar/dto/request/SeminarAttendanceCodeRequest.java
src/main/java/com/keeper/homepage/domain/seminar/dto/request/SeminarAttendanceStatusRequest.java
src/test/java/com/keeper/homepage/domain/seminar/api/SeminarApiTestHelper.java
src/test/java/com/keeper/homepage/domain/seminar/api/SeminarAttendanceControllerTest.java

close: #81
세미나 출석 상태 변경 기능을 구현했습니다!
Github Desktop이 편해서 사용하고 있는데 커밋 메세지가 또 짤렸네요... ....ㅠ

Feature/세미나 출석 상태 변경 구현

---

src/docs/asciidoc/library/book-manage.adoc
src/main/java/com/keeper/homepage/domain/library/api/BookManageController.kt
src/main/java/com/keeper/homepage/domain/library/application/BookManageService.kt
src/main/java/com/keeper/homepage/domain/library/entity/Book.java
src/main/java/com/keeper/homepage/domain/library/entity/BookBorrowInfo.java
src/main/java/com/keeper/homepage/domain/library/entity/BookBorrowStatus.java
src/main/java/com/keeper/homepage/domain/library/entity/BookDepartment.java
src/main/java/com/keeper/homepage/global/error/ErrorCode.java
src/test/java/com/keeper/homepage/domain/library/api/BookManageApiTestHelper.kt
src/test/java/com/keeper/homepage/domain/library/api/BookManageControllerTest.kt
src/test/java/com/keeper/homepage/domain/library/application/BookManageServiceTest.kt

close: #141
도서 삭제 기능을 제작해보았습미다
- 누군가가 대출한 상태라면 삭제 불가능
- 모든 책이 반납된 상태여야 함.
퇴근 후 개발
이게 워라밸이지

Feature/#141 도서 삭제 기능

---

src/docs/asciidoc/library/book-manage.adoc
src/main/java/com/keeper/homepage/domain/library/api/BorrowManageController.kt
src/main/java/com/keeper/homepage/domain/library/application/BorrowManageService.kt
src/main/java/com/keeper/homepage/domain/library/entity/Book.java
src/main/java/com/keeper/homepage/domain/library/entity/BookBorrowInfo.java
src/main/java/com/keeper/homepage/global/error/ErrorCode.java
src/test/java/com/keeper/homepage/domain/library/BookTestHelper.java
src/test/java/com/keeper/homepage/domain/library/api/BorrowManageApiTestHelper.kt
src/test/java/com/keeper/homepage/domain/library/api/BorrowManageControllerTest.kt

close: #137
대출 승인 / 거부 기능을 만들어봤습니다.

Feature/#137 대출 승인 거부 기능

---

src/docs/asciidoc/library/book-manage.adoc
src/main/java/com/keeper/homepage/domain/library/api/BorrowManageController.kt
src/main/java/com/keeper/homepage/domain/library/application/BorrowManageService.kt
src/main/java/com/keeper/homepage/domain/library/entity/Book.java
src/main/java/com/keeper/homepage/domain/library/entity/BookBorrowInfo.java
src/main/java/com/keeper/homepage/domain/library/entity/BookBorrowStatus.java
src/main/java/com/keeper/homepage/global/error/ErrorCode.java
src/test/java/com/keeper/homepage/domain/library/BookTestHelper.java
src/test/java/com/keeper/homepage/domain/library/api/BookManageControllerTest.kt
src/test/java/com/keeper/homepage/domain/library/api/BorrowManageApiTestHelper.kt
src/test/java/com/keeper/homepage/domain/library/api/BorrowManageControllerTest.kt

close: #139 
반납 승인 거절 기능을 추가해봤습니다.

Feature/#139 반납 승인 거절 기능

---

src/docs/asciidoc/library/book-manage.adoc
src/main/java/com/keeper/homepage/domain/library/api/BookManageController.kt
src/main/java/com/keeper/homepage/domain/library/api/BorrowManageController.kt
src/main/java/com/keeper/homepage/domain/library/application/BookManageService.kt
src/main/java/com/keeper/homepage/domain/library/application/BorrowManageService.kt
src/main/java/com/keeper/homepage/domain/library/dto/req/BookRequest.kt
src/main/java/com/keeper/homepage/domain/library/entity/Book.java
src/main/java/com/keeper/homepage/domain/library/entity/BookBorrowInfo.java
src/main/java/com/keeper/homepage/domain/library/entity/BookBorrowStatus.java
src/main/java/com/keeper/homepage/global/error/ErrorCode.java
src/main/java/com/keeper/homepage/global/error/ExceptionAdvice.java
src/test/java/com/keeper/homepage/IntegrationTest.java
src/test/java/com/keeper/homepage/domain/library/BookTestHelper.java
src/test/java/com/keeper/homepage/domain/library/api/BookManageApiTestHelper.kt
src/test/java/com/keeper/homepage/domain/library/api/BookManageControllerTest.kt
src/test/java/com/keeper/homepage/domain/library/api/BorrowManageApiTestHelper.kt
src/test/java/com/keeper/homepage/domain/library/api/BorrowManageControllerTest.kt
src/test/java/com/keeper/homepage/domain/library/application/BookManageServiceTest.kt

close: #142
도서 정보 수정 기능을 추가해봤습니다!
다들 화이팅입니다~!

Feature/#142 도서 정보 수정 기능

---

src/docs/asciidoc/library/book-manage.adoc
src/main/java/com/keeper/homepage/HomepageApplication.java
src/main/java/com/keeper/homepage/domain/library/api/BookManageController.kt
src/main/java/com/keeper/homepage/domain/library/api/BorrowManageController.kt
src/main/java/com/keeper/homepage/domain/library/application/BookManageService.kt
src/main/java/com/keeper/homepage/domain/library/application/BorrowManageService.kt
src/main/java/com/keeper/homepage/domain/library/converter/BorrowStatusDtoConverter.kt
src/main/java/com/keeper/homepage/domain/library/dao/BookBorrowInfoRepository.java
src/main/java/com/keeper/homepage/domain/library/dto/req/BookRequest.kt
src/main/java/com/keeper/homepage/domain/library/dto/req/BorrowStatusDto.kt
src/main/java/com/keeper/homepage/domain/library/dto/resp/BorrowResponse.kt
src/main/java/com/keeper/homepage/domain/library/entity/Book.java
src/main/java/com/keeper/homepage/domain/library/entity/BookBorrowInfo.java
src/main/java/com/keeper/homepage/domain/library/entity/BookBorrowStatus.java
src/main/java/com/keeper/homepage/global/config/web/WebMvcConfiguration.java
src/main/java/com/keeper/homepage/global/entity/BaseEntity.java
src/main/java/com/keeper/homepage/global/error/ErrorCode.java
src/main/java/com/keeper/homepage/global/error/ExceptionAdvice.java
src/test/java/com/keeper/homepage/IntegrationTest.java
src/test/java/com/keeper/homepage/domain/library/BookTestHelper.java
src/test/java/com/keeper/homepage/domain/library/api/BookManageApiTestHelper.kt
src/test/java/com/keeper/homepage/domain/library/api/BookManageControllerTest.kt
src/test/java/com/keeper/homepage/domain/library/api/BorrowManageApiTestHelper.kt
src/test/java/com/keeper/homepage/domain/library/api/BorrowManageControllerTest.kt
src/test/java/com/keeper/homepage/domain/library/application/BookManageServiceTest.kt

close: #138
close: #151
API URL 변경하는 김에 대출 상태에 따른 API 다 만들어봤습니다~!
평일에도 코딩 주말에도 코딩

Feature/#151 api uri 변경

---

src/docs/asciidoc/library/book-manage.adoc
src/main/java/com/keeper/homepage/HomepageApplication.java
src/main/java/com/keeper/homepage/domain/library/api/BookManageController.kt
src/main/java/com/keeper/homepage/domain/library/api/BorrowManageController.kt
src/main/java/com/keeper/homepage/domain/library/application/BookManageService.kt
src/main/java/com/keeper/homepage/domain/library/application/BorrowManageService.kt
src/main/java/com/keeper/homepage/domain/library/converter/BorrowStatusDtoConverter.kt
src/main/java/com/keeper/homepage/domain/library/dao/BookBorrowInfoRepository.java
src/main/java/com/keeper/homepage/domain/library/dto/req/BookRequest.kt
src/main/java/com/keeper/homepage/domain/library/dto/req/BorrowStatusDto.kt
src/main/java/com/keeper/homepage/domain/library/dto/resp/BookDetailResponse.kt
src/main/java/com/keeper/homepage/domain/library/dto/resp/BorrowDetailResponse.kt
src/main/java/com/keeper/homepage/domain/library/dto/resp/BorrowResponse.kt
src/main/java/com/keeper/homepage/domain/library/entity/Book.java
src/main/java/com/keeper/homepage/domain/library/entity/BookBorrowInfo.java
src/main/java/com/keeper/homepage/domain/library/entity/BookBorrowStatus.java
src/main/java/com/keeper/homepage/domain/thumbnail/entity/Thumbnail.java
src/main/java/com/keeper/homepage/global/config/web/WebMvcConfiguration.java
src/main/java/com/keeper/homepage/global/entity/BaseEntity.java
src/main/java/com/keeper/homepage/global/error/ErrorCode.java
src/main/java/com/keeper/homepage/global/error/ExceptionAdvice.java
src/test/java/com/keeper/homepage/IntegrationTest.java
src/test/java/com/keeper/homepage/domain/library/api/BookManageApiTestHelper.kt
src/test/java/com/keeper/homepage/domain/library/api/BookManageControllerTest.kt
src/test/java/com/keeper/homepage/domain/library/api/BorrowManageApiTestHelper.kt
src/test/java/com/keeper/homepage/domain/library/api/BorrowManageControllerTest.kt
src/test/java/com/keeper/homepage/domain/library/application/BookManageServiceTest.kt

close: #143
책 상세 정보 보기로 기능을 바꾸었습니다.
갈수록 짧아지는 테스트코드들 ㅎㅎ...

특정 책의 대출 정보 조회 기능 -> 책 상세 정보 API

---

src/main/java/com/keeper/homepage/domain/library/application/BorrowManageService.kt
src/main/java/com/keeper/homepage/domain/library/dto/req/BorrowStatusDto.kt

close: 없음.
이현님의 훌륭한 질문을 바탕으로 OCP를 유지하는 코드를 만들어 봤습니다.
`switch`와 다르게 `when`의 경우 모든 관련 클래스나 객체에 대해서 처리를 해주지 않으면 컴파일 에러가 발생하기에 그저 안전하다고 생각했었는데, OCP 유지가 안되는 문제가 있었네요 ㅎㅎ
회사생활 대-꿀잼

refactor: OCP 준수해보기

---

src/test/java/com/keeper/homepage/domain/library/api/BorrowManageControllerTest.kt

close: 없음.
삽질 엄청 했네요...
여러분 Jackson에서 formatting할 땐 반올림을 해주고 DateTimeFormat으로 formatting할 땐 버림을 합니다...!
https://stackoverflow.com/questions/72827225/how-can-i-compare-localdatetime-in-json-after-parsing-it-out-of-an-object-with-t
아이고 아이고

fix: Datetime 포맷팅 문제 해결

---

src/docs/asciidoc/library/book-manage.adoc
src/main/java/com/keeper/homepage/domain/library/api/BookManageController.kt
src/main/java/com/keeper/homepage/domain/library/application/BookManageService.kt
src/main/java/com/keeper/homepage/domain/library/dto/req/ModifyBookRequest.kt
src/main/java/com/keeper/homepage/domain/library/entity/Book.java
src/test/java/com/keeper/homepage/domain/library/api/BookManageApiTestHelper.kt
src/test/java/com/keeper/homepage/domain/library/api/BookManageControllerTest.kt
src/test/java/com/keeper/homepage/domain/library/api/BorrowManageControllerTest.kt
src/test/java/com/keeper/homepage/domain/library/application/BookManageServiceTest.kt

없음!
책 정보 수정할 때 썸네일을 함께 보내주도록 되어 있어서 비효율적이었습니다.
이를 분리함으로써 개선하였습니다.
놀금 너무좋아요~

feat: 책 정보 수정 API와 책 썸네일 수정 API를 서로 분리

---

src/main/java/com/keeper/homepage/domain/library/application/BookManageService.kt
src/main/java/com/keeper/homepage/domain/library/application/BorrowManageService.kt
src/main/java/com/keeper/homepage/domain/library/entity/Book.java
src/test/java/com/keeper/homepage/domain/library/BookBorrowInfoTestHelper.java
src/test/java/com/keeper/homepage/domain/library/BookTestHelper.java
src/test/java/com/keeper/homepage/domain/library/api/BorrowManageControllerTest.kt
src/test/java/com/keeper/homepage/domain/library/application/BookManageServiceTest.kt
src/test/java/com/keeper/homepage/domain/library/dao/BookRepositoryTest.java

없음!
DB 수정사항 반영
빠른 리뷰 부탁드립니다~!

fix: Book Entity의 currentQuantity 컬럼 제거

---

src/docs/asciidoc/post/post.adoc
src/main/java/com/keeper/homepage/domain/post/api/PostController.java
src/main/java/com/keeper/homepage/domain/post/application/PostService.java
src/main/java/com/keeper/homepage/domain/post/dto/request/PostUpdateRequest.java
src/test/java/com/keeper/homepage/domain/post/api/PostApiTestHelper.java
src/test/java/com/keeper/homepage/domain/post/api/PostControllerTest.java
src/test/java/com/keeper/homepage/domain/post/application/PostServiceTest.java

close: #160
게시글 수정 API를 게시글 내용 수정 API, 게시글 썸네일 수정 API로 분리하였습니다!

Feature/게시글 수정 썸네일 수정 api 분리

---

src/main/java/com/keeper/homepage/domain/survey/converter/SurveyReplyTypeConverter.java
src/main/java/com/keeper/homepage/domain/survey/dao/SurveyMemberReplyRepository.java
src/main/java/com/keeper/homepage/domain/survey/dao/SurveyReplyExcuseRepository.java
src/main/java/com/keeper/homepage/domain/survey/dao/SurveyReplyRepository.java
src/main/java/com/keeper/homepage/domain/survey/dao/SurveyRepository.java
src/main/java/com/keeper/homepage/domain/survey/entity/Survey.java
src/main/java/com/keeper/homepage/domain/survey/entity/SurveyMemberReply.java
src/main/java/com/keeper/homepage/domain/survey/entity/SurveyReply.java
src/main/java/com/keeper/homepage/domain/survey/entity/SurveyReplyExcuse.java
src/main/java/com/keeper/homepage/global/error/ErrorCode.java
src/test/java/com/keeper/homepage/IntegrationTest.java
src/test/java/com/keeper/homepage/domain/survey/SurveyMemberReplyTestHelper.java
src/test/java/com/keeper/homepage/domain/survey/SurveyTestHelper.java
src/test/java/com/keeper/homepage/domain/survey/dao/SurveyMemberReplyRepositoryTest.java
src/test/java/com/keeper/homepage/domain/survey/dao/SurveyReplyRepositoryTest.java
src/test/java/com/keeper/homepage/domain/survey/dao/SurveyRepositoryTest.java

close: #5
활동 조사 엔티티와 레포지토리를 개발하였고, 관련된 테스트를 작성하였습니다.
새로 개발 배우고 싶으신 분들께 설명 드릴 겸 해서 개발해봤습니다! 예전에 제가 개발했던 파트여서 기억이 새록새록 났습니다 ㅎㅎ
과제 보단 개발이죠 ㅎㅎㅋㅋ

Feature/활동조사 entity repository 개발

---

src/docs/asciidoc/post/post.adoc
src/main/java/com/keeper/homepage/domain/comment/application/CommentService.java
src/main/java/com/keeper/homepage/domain/comment/dto/response/CommentResponse.java
src/main/java/com/keeper/homepage/domain/comment/entity/Comment.java
src/main/java/com/keeper/homepage/domain/member/entity/Member.java
src/main/java/com/keeper/homepage/domain/post/api/PostController.java
src/main/java/com/keeper/homepage/domain/post/application/PostService.java
src/main/java/com/keeper/homepage/domain/post/application/convenience/CategoryFindService.java
src/main/java/com/keeper/homepage/domain/post/dao/PostRepository.java
src/main/java/com/keeper/homepage/domain/post/dao/category/CategoryRepository.java
src/main/java/com/keeper/homepage/domain/post/dto/response/PostDetailResponse.java
src/main/java/com/keeper/homepage/domain/post/dto/response/PostListResponse.java
src/main/java/com/keeper/homepage/domain/post/dto/response/PostResponse.java
src/main/java/com/keeper/homepage/domain/post/dto/response/PostWriteResponse.java
src/main/java/com/keeper/homepage/domain/post/entity/Post.java
src/test/java/com/keeper/homepage/domain/post/PostTestHelper.java
src/test/java/com/keeper/homepage/domain/post/api/PostApiTestHelper.java
src/test/java/com/keeper/homepage/domain/post/api/PostControllerTest.java
src/test/java/com/keeper/homepage/domain/post/application/PostServiceTest.java

close: #169
- 공지글 목록 조회 api 구현 
- 전체적으로 게시글 파트 리팩토링 (중복 코드 제거, `Optional` 사용 등등)
을 진행했습니다. 
리팩토링 할 때 커밋을 분리하는 연습이 필요한 것 같습니다...!

Feature/공지글 목록 조회

---

src/main/java/com/keeper/homepage/domain/study/entity/Study.java
src/test/java/com/keeper/homepage/domain/study/StudyTestHelper.java
src/test/java/com/keeper/homepage/domain/study/dao/StudyRepositoryTest.java

close: 없음
`member_count` 컬럼 제거 반영
리뷰 소요시간 : 1초~!

fix: member_count 컬럼 제거 반영

---

src/main/java/com/keeper/homepage/domain/library/api/BookController.java
src/main/java/com/keeper/homepage/domain/library/application/BookService.java
src/main/java/com/keeper/homepage/domain/library/dao/BookRepository.java
src/main/java/com/keeper/homepage/domain/library/dto/resp/BookResponse.java
src/main/java/com/keeper/homepage/domain/library/entity/Book.java
src/main/java/com/keeper/homepage/global/error/ErrorCode.java
src/test/java/com/keeper/homepage/domain/library/api/BookApiTestHelper.java
src/test/java/com/keeper/homepage/domain/library/api/BookControllerTest.java

close: #161 
검색 조건(전체, 도서 명, 저자)에 따라서 도서 목록을 조회한다.
화이팅~ 해야지~

Feature/도서 목록 조회 구현

---

src/docs/asciidoc/member/member.adoc
src/main/java/com/keeper/homepage/domain/member/api/MemberRankController.java
src/main/java/com/keeper/homepage/domain/member/application/MemberRankService.java
src/main/java/com/keeper/homepage/domain/member/dao/MemberRepository.java
src/main/java/com/keeper/homepage/domain/member/dto/response/MemberPointRankResponse.java
src/main/java/com/keeper/homepage/domain/member/entity/Member.java
src/test/java/com/keeper/homepage/domain/member/api/MemberRankApiTestHelper.java
src/test/java/com/keeper/homepage/domain/member/api/MemberRankControllerTest.java
src/test/java/com/keeper/homepage/global/restdocs/RestDocsHelper.java

close: #174
누적 포인트 랭킹 조회 기능을 구현했습니다! 추가로 page helper 메서드도 RestDocsHelper에 만들어봤습니다!!
내일 밤은 stayC와 함께 실험을 할 예정입니다ㅣ ㅎㅎ

Feature/포인트 랭킹 구현

---

src/docs/asciidoc/keeper.adoc
src/docs/asciidoc/library/book.adoc
src/main/java/com/keeper/homepage/domain/library/api/BookController.java
src/main/java/com/keeper/homepage/domain/library/application/BookService.java
src/main/java/com/keeper/homepage/domain/library/dao/BookRepository.java
src/test/java/com/keeper/homepage/domain/library/api/BookApiTestHelper.java
src/test/java/com/keeper/homepage/domain/library/api/BookControllerTest.java
src/test/java/com/keeper/homepage/global/restdocs/RestDocsHelper.java

close: 없음
프론트에 문서 전달할려다가 문서가 없음을 발견했네요~
리뷰 소요시간 : 1분

Feature/도서 api 작성 및 리팩토링

---

src/docs/asciidoc/game/baseball.adoc
src/main/java/com/keeper/homepage/domain/game/api/GameController.kt
src/main/java/com/keeper/homepage/domain/game/application/BaseballService.kt
src/main/java/com/keeper/homepage/domain/game/dto/BaseballResult.kt
src/main/java/com/keeper/homepage/domain/game/dto/req/BaseballGuessResponse.kt
src/main/java/com/keeper/homepage/domain/game/support/BaseballSupport.kt
src/test/java/com/keeper/homepage/domain/game/api/GameApiTestHelper.kt
src/test/java/com/keeper/homepage/domain/game/api/GameControllerTest.kt
src/test/java/com/keeper/homepage/domain/game/support/BaseballSupportTest.kt

close: 없음
야구게임 API에 GET API 하나 추가
화이팅입니다~!

Feature/야구게임 get api 추가

---

src/docs/asciidoc/library/book.adoc
src/main/java/com/keeper/homepage/domain/library/api/BookController.java
src/main/java/com/keeper/homepage/domain/library/application/BookService.java
src/main/java/com/keeper/homepage/domain/library/dao/BookBorrowInfoRepository.java
src/main/java/com/keeper/homepage/domain/member/entity/Member.java
src/main/java/com/keeper/homepage/global/error/ErrorCode.java
src/test/java/com/keeper/homepage/IntegrationTest.java
src/test/java/com/keeper/homepage/domain/library/api/BookApiTestHelper.java
src/test/java/com/keeper/homepage/domain/library/api/BookControllerTest.java
src/test/java/com/keeper/homepage/domain/library/application/BookServiceTest.java

close: #162
도서 대출 신청 api 구현
저만 다음주 월요일에 수업하나요?

feat : 도서 대출 신청 api 구현

---

.github/workflows/gpt_review.yml

close: #186
깃허브 코드리뷰 설정입니다! 이제야 적용해보네요...
앞으로 gpt review 라벨을 달면 리뷰가 되도록 설정 추가했습니다! 프론트 yml 참고하였어요 짱짱굿...
종강했습니다 ㅎㅎ 이번 학기는 쉽지 않았어요 정말~!

chore: gpt code review 설정

---

src/docs/asciidoc/study/study.adoc
src/main/java/com/keeper/homepage/domain/member/application/convenience/MemberFindService.java
src/main/java/com/keeper/homepage/domain/member/dao/MemberRepository.java
src/main/java/com/keeper/homepage/domain/study/api/StudyController.java
src/main/java/com/keeper/homepage/domain/study/application/StudyService.java
src/main/java/com/keeper/homepage/domain/study/dao/StudyHasMemberRepository.java
src/main/java/com/keeper/homepage/domain/study/dto/request/StudyUpdateRequest.java
src/main/java/com/keeper/homepage/domain/study/entity/Study.java
src/test/java/com/keeper/homepage/domain/study/api/StudyApiTestHelper.java
src/test/java/com/keeper/homepage/domain/study/api/StudyControllerTest.java
src/test/java/com/keeper/homepage/domain/study/application/StudyServiceTest.java

close: #176
close: #198
close: #199
- 스터디원 추가 & 삭제 기능 구현
- 스터디 수정 + 스터디 썸네일 수정 기능 구현
- 스터디장만 접근할 수 있어야 함 ([기획서](https://www.notion.so/A1-A9-a9b13c9075f548c79f5f7408d113a2e9?pvs=4))
PR 단위가 조금 크네요...! 이번 기능들은 로직이 크게 없었네요!

Feature/스터디원 추가 삭제 구현 + 스터디 수정, 썸네일 수정 기능 구현

---

src/test/java/com/keeper/homepage/domain/study/application/StudyServiceTest.java

close: #없음
@Test 안으로 데이터 생성 코드 옮김
주의해야겠습니다...!

fix: 테스트 데이터 롤백 안되는 문제 해결

---

src/docs/asciidoc/game/game.adoc
src/main/java/com/keeper/homepage/domain/game/api/GameController.kt
src/main/java/com/keeper/homepage/domain/game/application/GameFindService.kt
src/main/java/com/keeper/homepage/domain/game/application/GameService.kt
src/main/java/com/keeper/homepage/domain/game/dao/GameRepository.java
src/main/java/com/keeper/homepage/domain/game/dto/res/GameRankResponse.kt
src/main/java/com/keeper/homepage/domain/game/entity/embedded/Dice.java
src/main/java/com/keeper/homepage/domain/game/entity/embedded/Lotto.java
src/main/java/com/keeper/homepage/domain/game/entity/embedded/Roulette.java
src/test/java/com/keeper/homepage/IntegrationTest.java
src/test/java/com/keeper/homepage/domain/game/GameTestHelper.java
src/test/java/com/keeper/homepage/domain/game/api/GameApiTestHelper.kt
src/test/java/com/keeper/homepage/domain/game/api/GameControllerTest.kt
src/test/java/com/keeper/homepage/domain/game/application/GameServiceTest.kt

Feature/#175 게임 랭킹 기능 구현

---

src/docs/asciidoc/auth/auth.adoc
src/main/java/com/keeper/homepage/domain/auth/api/SignInController.java
src/main/java/com/keeper/homepage/domain/auth/application/SignInService.java
src/test/java/com/keeper/homepage/domain/auth/api/SignInControllerTest.java

없음.
로그인 시 회원 권한도 응답에 담아서 보내도록 변경했습니다.
비가 많이 오네요... 다들 조심하세용

로그인 시 회원 권한도 respose 하도록 변경

---

src/main/java/com/keeper/homepage/domain/library/application/BorrowManageService.kt

close: #225
이슈와 동일합니다.
백엔드 개발도 끝이 보이네요 ㅎㅎ...

대출 승인할 때에도 대출 가능한 책이 있는지 확인

---

src/main/java/com/keeper/homepage/domain/member/entity/job/MemberJob.java
src/main/java/com/keeper/homepage/domain/post/application/PostService.java
src/main/java/com/keeper/homepage/domain/post/dto/response/PostDetailResponse.java
src/main/java/com/keeper/homepage/domain/post/entity/category/Category.java
src/test/java/com/keeper/homepage/domain/post/CategoryTestHelper.java
src/test/java/com/keeper/homepage/domain/post/api/PostControllerTest.java
src/test/java/com/keeper/homepage/domain/post/application/PostServiceTest.java
src/test/java/com/keeper/homepage/domain/post/dao/category/CategoryRepositoryTest.java

> close: #231, close: #234
- member_job
- ROLE_INFRA_전산관리자 직책이 추가되었습니다.
- category
- 사용하지 않는 컬럼인 parent_id와 href를 지웠습니다.
- 사용하지 않는 데이터들을 정리하고, 프론트와 맞춰서 사용하게 될 카테고리 데이터를 추가했습니다.

Feature/0724 db 변경사항 반영

---

src/main/java/com/keeper/homepage/domain/ctf/dao/CtfContestRepository.java
src/main/java/com/keeper/homepage/domain/ctf/dao/team/CtfTeamHasMemberRepository.java
src/main/java/com/keeper/homepage/domain/ctf/dao/team/CtfTeamRepository.java
src/main/java/com/keeper/homepage/domain/ctf/entity/CtfContest.java
src/main/java/com/keeper/homepage/domain/ctf/entity/team/CtfTeam.java
src/main/java/com/keeper/homepage/domain/ctf/entity/team/CtfTeamHasMember.java
src/main/java/com/keeper/homepage/domain/ctf/entity/team/CtfTeamHasMemberPK.java
src/main/java/com/keeper/homepage/domain/member/entity/Member.java
src/test/java/com/keeper/homepage/IntegrationTest.java
src/test/java/com/keeper/homepage/domain/ctf/CtfContestTestHelper.java
src/test/java/com/keeper/homepage/domain/ctf/CtfTeamTestHelper.java
src/test/java/com/keeper/homepage/domain/ctf/dao/CtfTeamRepositoryTest.java

issue: #10
CtfTeam, CtfContest의 엔티티와 레파지토리를 개발했습니다.
CTF 개발시작..!!

Feature/ctf team, contest entity repository 개발

---

src/main/java/com/keeper/homepage/domain/game/dto/res/GameRankResponse.kt
src/main/java/com/keeper/homepage/domain/library/dto/resp/BookDetailResponse.kt
src/main/java/com/keeper/homepage/domain/library/entity/Book.java
src/main/java/com/keeper/homepage/domain/member/entity/Member.java
src/main/java/com/keeper/homepage/domain/post/dao/PostRepository.java
src/main/java/com/keeper/homepage/domain/post/entity/Post.java
src/main/java/com/keeper/homepage/domain/study/entity/Study.java
src/main/java/com/keeper/homepage/domain/thumbnail/entity/Thumbnail.java
src/test/java/com/keeper/homepage/domain/post/application/PostServiceTest.java

Feature/#267 썸네일 디폴트 이미지 응답 처리

---

src/main/java/com/keeper/homepage/domain/library/api/BorrowManageController.kt
src/main/java/com/keeper/homepage/domain/library/application/BookService.java
src/main/java/com/keeper/homepage/domain/library/application/BorrowManageService.kt
src/main/java/com/keeper/homepage/domain/library/dao/BookBorrowInfoRepository.java
src/main/java/com/keeper/homepage/domain/library/dto/req/BorrowStatusDto.kt
src/main/java/com/keeper/homepage/domain/library/dto/resp/BorrowDetailResponse.kt
src/main/java/com/keeper/homepage/domain/library/entity/BookBorrowInfo.java
src/test/java/com/keeper/homepage/domain/library/api/BookManageApiTestHelper.kt
src/test/java/com/keeper/homepage/domain/library/api/BorrowManageControllerTest.kt

> close: #248
> close: #249 
검색 가능하도록 변경
연체 도서 조회 시 lastRequestDate 추가
> 테스트가 너무 길어지네용 ㅎㅎ
놀금 좋아~ 👍😄

도서 관리자 추가 요청 사항 반영

---

src/main/java/com/keeper/homepage/domain/library/application/BookService.java
src/main/java/com/keeper/homepage/domain/library/entity/BookBorrowInfo.java

> close: X
> 불필요한 파라미터 제거
이전 PR에서 제거가 안되어있어서 수정했습니다~

chore: 불필요한 파라미터 제거

---

src/docs/asciidoc/attendance/attendance.adoc
src/main/java/com/keeper/homepage/domain/attendance/api/AttendanceController.java
src/main/java/com/keeper/homepage/domain/attendance/application/AttendanceService.java
src/main/java/com/keeper/homepage/domain/attendance/dao/AttendanceRepository.java
src/main/java/com/keeper/homepage/domain/attendance/dto/response/AttendanceInfoResponse.java
src/main/java/com/keeper/homepage/domain/attendance/dto/response/AttendancePointResponse.java
src/main/java/com/keeper/homepage/domain/attendance/dto/response/AttendanceRankResponse.java
src/main/java/com/keeper/homepage/domain/attendance/dto/response/AttendanceResponse.java
src/main/java/com/keeper/homepage/global/error/ErrorCode.java
src/test/java/com/keeper/homepage/domain/attendance/api/AttendanceControllerTest.java

> close: #280
프로필 수정/관리 페이지에서 필요할 출석부 기능을 구현했습니다. [기획서 링크](https://www.notion.so/B1-B6-cdb04ea37e8440809b00e3ad129c2bbb?pvs=4) 참고하시면 될 것 같아요!
+) 아직 출석 정보 목록 조회에서 어떤 응답이 사용될 지는 의논된 바가 없어서 일단 id랑 출석 날짜만 보내게 짰습니다.
프론트 UI 너무 예쁜것같아요..😆

Feature/출석부 기능 구현

---

src/docs/asciidoc/election/election-manage.adoc
src/docs/asciidoc/keeper.adoc
src/main/java/com/keeper/homepage/domain/election/api/AdminElectionController.java
src/main/java/com/keeper/homepage/domain/election/application/AdminElectionService.java
src/main/java/com/keeper/homepage/domain/election/application/convenience/ElectionDeleteService.java
src/main/java/com/keeper/homepage/domain/election/application/convenience/ValidElectionFindService.java
src/main/java/com/keeper/homepage/domain/election/dao/ElectionRepository.java
src/main/java/com/keeper/homepage/domain/election/dao/ElectionVoterRepository.java
src/main/java/com/keeper/homepage/domain/election/entity/Election.java
src/main/java/com/keeper/homepage/global/error/ErrorCode.java
src/test/java/com/keeper/homepage/domain/election/api/AdminElectionApiTestHelper.java
src/test/java/com/keeper/homepage/domain/election/api/AdminTestElectionControllerTest.java
src/test/java/com/keeper/homepage/domain/election/application/AdminElectionServiceTest.java

> close: #253
> 선거 삭제 기능 구현했습니다
> 이렇게 삭제하면 선거, 후보자, 투표자, 로그 다 삭제되는거 맞겠죠..?

Feature/선거 삭제 기능 구현

---

src/docs/asciidoc/game/baseball.adoc
src/main/java/com/keeper/homepage/domain/game/api/GameController.kt
src/main/java/com/keeper/homepage/domain/game/application/BaseballService.kt
src/main/java/com/keeper/homepage/domain/game/dto/res/BaseballResponse.kt
src/main/java/com/keeper/homepage/domain/game/entity/redis/BaseballResultEntity.kt
src/test/java/com/keeper/homepage/domain/game/api/GameApiTestHelper.kt
src/test/java/com/keeper/homepage/domain/game/api/GameControllerTest.kt

시작시에 earnable Points 내리도록 변경
오펜하이머 꿀잼

야구게임 시작시 earnable Point 내리도록 변경

---

src/docs/asciidoc/election/election-manage.adoc
src/main/java/com/keeper/homepage/domain/election/api/AdminElectionController.java
src/main/java/com/keeper/homepage/domain/election/application/AdminElectionService.java
src/main/java/com/keeper/homepage/domain/election/dto/request/ElectionCreateRequest.java
src/main/java/com/keeper/homepage/domain/election/dto/request/ElectionUpdateRequest.java
src/main/java/com/keeper/homepage/domain/election/entity/Election.java
src/test/java/com/keeper/homepage/domain/election/api/AdminElectionApiTestHelper.java
src/test/java/com/keeper/homepage/domain/election/api/AdminTestElectionControllerTest.java

> close: #252
> 선거 수정 기능을 구현했습니다.
> `ElectionCreateRequest`랑 `ElectionUpdateRequest`가 내용이 같은데, 그래도 따로 두는게 더 낫겠죠?

Feature/선거 수정 기능 구현

---

src/docs/asciidoc/election/election-manage.adoc
src/main/java/com/keeper/homepage/domain/election/api/AdminElectionController.java
src/main/java/com/keeper/homepage/domain/election/application/AdminElectionService.java
src/main/java/com/keeper/homepage/domain/election/application/convenience/ValidElectionFindService.java
src/main/java/com/keeper/homepage/domain/election/dao/ElectionRepository.java
src/main/java/com/keeper/homepage/domain/election/dto/request/ElectionCreateRequest.java
src/main/java/com/keeper/homepage/domain/election/dto/request/ElectionUpdateRequest.java
src/main/java/com/keeper/homepage/domain/election/dto/response/ElectionResponse.java
src/main/java/com/keeper/homepage/domain/election/entity/Election.java
src/test/java/com/keeper/homepage/domain/election/ElectionTestHelper.java
src/test/java/com/keeper/homepage/domain/election/api/AdminElectionApiTestHelper.java
src/test/java/com/keeper/homepage/domain/election/api/AdminTestElectionControllerTest.java

> close: #254
> 선거 목록 조회 기능을 구현했습니당

Feature/선거 목록 조회 기능 구현

---

src/docs/asciidoc/game/baseball.adoc
src/main/java/com/keeper/homepage/domain/game/api/GameController.kt
src/main/java/com/keeper/homepage/domain/game/application/BaseballService.kt
src/main/java/com/keeper/homepage/domain/game/dto/res/BaseballStatusResponse.kt
src/main/java/com/keeper/homepage/domain/game/dto/res/GameInfoByMemberResponse.kt
src/main/java/com/keeper/homepage/domain/game/entity/embedded/Baseball.java
src/main/java/com/keeper/homepage/domain/game/entity/redis/BaseballResultEntity.kt
src/test/java/com/keeper/homepage/domain/game/api/GameApiTestHelper.kt
src/test/java/com/keeper/homepage/domain/game/api/GameControllerTest.kt

> close: 없음
1. 이제 게임이 시작했는지 대신 게임의 현재 상태를 보내줍니다.
2. 4strike가 됐는데도 이후 계속 null이 추가되는 문제를 해결했습니다.
또 봐용~

야구게임 추가 사항

---

src/docs/asciidoc/member/member.adoc
src/main/java/com/keeper/homepage/domain/member/api/MemberController.java
src/main/java/com/keeper/homepage/domain/member/application/MemberProfileService.java
src/main/java/com/keeper/homepage/domain/member/entity/Member.java
src/main/java/com/keeper/homepage/domain/member/entity/embedded/Profile.java
src/test/java/com/keeper/homepage/IntegrationTest.java
src/test/java/com/keeper/homepage/domain/member/api/MemberControllerTest.java
src/test/java/com/keeper/homepage/domain/member/application/MemberProfileServiceTest.java

close: #72
프로필/프로필 수정 페이지의 G2 부분인 프로필 썸네일 수정 기능을 완성했습니다...!!!
이미 ThumbnailUtil 이랑 기반을 잘 닦아주셔가지고 만들어 두신 기능 사용할 때 넘 좋았습니다~~👍
짜두신 코드 한번 더 공부해보도록 하겠습니닷!! 좋은 코드 감사합니당

Feature/프로필 썸네일 수정

---

src/main/java/com/keeper/homepage/domain/auth/application/AuthCookieService.java
src/main/java/com/keeper/homepage/global/config/security/filter/RefreshTokenFilter.java

> close: 없음.
[해결 노션](https://devblog-gusah009.notion.site/KEEPER-e0df1d23efcf4232898556767ac47e04?pvs=4)
간만에 디버깅 오래 했네요... 스프링 MVC 공부를 열심히 해놓길 잘했습니다...ㅎㅎ

로그인 안되던 문제 진짜 진짜 해결

---

src/docs/asciidoc/election/election-manage.adoc
src/main/java/com/keeper/homepage/domain/election/api/AdminElectionController.java
src/main/java/com/keeper/homepage/domain/election/application/AdminElectionService.java
src/main/java/com/keeper/homepage/domain/election/application/convenience/ValidCandidateService.java
src/main/java/com/keeper/homepage/domain/election/application/convenience/ValidElectionFindService.java
src/main/java/com/keeper/homepage/domain/election/dao/ElectionCandidateRepository.java
src/main/java/com/keeper/homepage/domain/election/dao/ElectionRepository.java
src/main/java/com/keeper/homepage/domain/election/dto/request/ElectionCandidateRegisterRequest.java
src/main/java/com/keeper/homepage/domain/election/dto/request/ElectionCandidatesRegisterRequest.java
src/main/java/com/keeper/homepage/domain/election/entity/ElectionCandidate.java
src/main/java/com/keeper/homepage/global/error/ErrorCode.java
src/test/java/com/keeper/homepage/IntegrationTest.java
src/test/java/com/keeper/homepage/domain/election/ElectionCandidateTestHelper.java
src/test/java/com/keeper/homepage/domain/election/ElectionTestHelper.java
src/test/java/com/keeper/homepage/domain/election/ElectionVoterTestHelper.java
src/test/java/com/keeper/homepage/domain/election/api/AdminElectionApiTestHelper.java
src/test/java/com/keeper/homepage/domain/election/api/AdminTestElectionControllerTest.java
src/test/java/com/keeper/homepage/domain/election/application/AdminElectionServiceTest.java

> close: #305
> 선거 후보자 등록 및 삭제 기능을 구현했습니다.
> 선거 후보자 다중 등록 기능을 구현했습니다.
> 이 이슈 merge 되면 나머지 이슈 2개는 한 번에 하겠습니당~

Feature/선거 후보자 등록 및 삭제 기능 구현

---

src/docs/asciidoc/member/member.adoc
src/main/java/com/keeper/homepage/domain/member/api/MemberController.java
src/main/java/com/keeper/homepage/domain/member/application/MemberService.java
src/main/java/com/keeper/homepage/domain/member/dto/request/UpdateMemberTypeRequest.java
src/main/java/com/keeper/homepage/domain/member/entity/Member.java
src/main/java/com/keeper/homepage/domain/member/entity/type/MemberType.java
src/main/java/com/keeper/homepage/global/error/ErrorCode.java
src/test/java/com/keeper/homepage/domain/member/api/MemberControllerTest.java
src/test/java/com/keeper/homepage/domain/member/application/MemberServiceTest.java

close: #318
회원 타입 변경 기능을 만들었습니다..!

Feature/회원 타입 변경 기능

---

src/main/java/com/keeper/homepage/domain/library/api/BookController.java
src/main/java/com/keeper/homepage/domain/library/api/BookManageController.kt
src/main/java/com/keeper/homepage/domain/library/application/BookManageService.kt
src/main/java/com/keeper/homepage/domain/library/application/BookService.java
src/main/java/com/keeper/homepage/domain/library/converter/BookSearchTypeConverter.kt
src/main/java/com/keeper/homepage/domain/library/dao/BookRepository.java
src/main/java/com/keeper/homepage/domain/library/dto/req/BookSearchType.kt
src/main/java/com/keeper/homepage/domain/library/dto/resp/BookBorrowResponse.java
src/main/java/com/keeper/homepage/domain/library/dto/resp/BookDetailResponse.kt
src/test/java/com/keeper/homepage/domain/library/api/BookApiTestHelper.java
src/test/java/com/keeper/homepage/domain/library/api/BookManageApiTestHelper.kt
src/test/java/com/keeper/homepage/domain/library/api/BookManageControllerTest.kt
src/test/java/com/keeper/homepage/domain/library/application/BookServiceTest.java

> close: 없음.
@JJimini @02ggang9 님들의 코드 수정 사항이 있어서 적절한지 봐주시면 감사하겠습니다.
- String으로 들어오던 `searchType`을 enum화
- Spring Param 어노테이션을 쓰지 않고 다른 어노테이션을 사용해 문제가 생기던 부분 수정
프론트 전달사항)
- 도서 관리 목록 조회 시 검색타입 추가 (`searchType`)
- 도서 관리 목록 조회 응답값 변경
- id -> bookId
- totalCount -> totalQuantity
- borrowingCount -> currentQuantity (아예 내용이 달라졌습니다)
- 도서 대여 정보 응답값 변경
- title -> bookTitke
- borrowDate -> borrowDateTime
- expireDate -> expireDateTime
관련 슬랙
https://keepernewhome-5o41027.slack.com/archives/C04MA6U2K96/p1693043460989459
벌써 일요일...

도서 수정사항 반영

---

src/docs/asciidoc/election/election-manage.adoc
src/main/java/com/keeper/homepage/domain/election/api/AdminElectionController.java
src/main/java/com/keeper/homepage/domain/election/application/AdminElectionService.java
src/main/java/com/keeper/homepage/domain/election/application/convenience/ValidVoterService.java
src/main/java/com/keeper/homepage/domain/election/dao/ElectionVoterRepository.java
src/main/java/com/keeper/homepage/domain/election/dto/request/ElectionVotersRequest.java
src/main/java/com/keeper/homepage/domain/election/entity/Election.java
src/main/java/com/keeper/homepage/global/error/ErrorCode.java
src/test/java/com/keeper/homepage/domain/election/api/AdminElectionApiTestHelper.java
src/test/java/com/keeper/homepage/domain/election/api/AdminTestElectionControllerTest.java
src/test/java/com/keeper/homepage/domain/election/application/AdminElectionServiceTest.java

> close: #303
> close: #306
> 선거 투표권자 등록 및 삭제 기능 구현
선거 공개 및 비공개 기능 구현
> 선거 페이지의 마지막 기능이네용
저는 일요일에 돌아오겠습니다~!

Feature/선거 투표권자 등록과 삭제 및 선거 공개와 비공개 기능 구현

---

src/main/java/com/keeper/homepage/domain/post/dto/response/MainPostResponse.java
src/main/java/com/keeper/homepage/domain/post/dto/response/MemberPostResponse.java
src/main/java/com/keeper/homepage/domain/post/dto/response/PostDetailResponse.java
src/main/java/com/keeper/homepage/domain/post/dto/response/PostResponse.java
src/main/java/com/keeper/homepage/domain/post/dto/response/TempPostResponse.java

> close: #없음
프론트의 요청사항 입니다.
머지되면 알려주기 / 간단한 작업이라 approve 없이 머지하겠습니다~

fix: registerTime 응답 형식 "yyyy-mm-dd"로 변경

---

src/main/java/com/keeper/homepage/domain/game/application/BaseballService.kt
src/test/java/com/keeper/homepage/domain/game/api/GameApiTestHelper.kt
src/test/java/com/keeper/homepage/domain/game/api/GameControllerTest.kt

> close: 없음.
말도 안되던 버그를 수정했습니다.
사내 CTF에서 문제 다풀어서 텀블러 받았네요~ 여러분 보안도 이렇게 중요합니당

fix: 야구 게임 guess 할 때 마다 점수 부여하던 버그 수정

---

src/docs/asciidoc/post/post.adoc
src/main/java/com/keeper/homepage/domain/post/api/PostController.java
src/main/java/com/keeper/homepage/domain/post/application/PostService.java
src/main/java/com/keeper/homepage/domain/post/dto/request/PostFileDeleteRequest.java
src/test/java/com/keeper/homepage/domain/post/api/PostApiTestHelper.java
src/test/java/com/keeper/homepage/domain/post/api/PostControllerTest.java
src/test/java/com/keeper/homepage/domain/post/application/PostServiceTest.java

fix: 게시글 파일 다중 삭제 api로 변경

---

.github/workflows/deploy-development.yml

> close: #
> debug 옵션 켠 후 github action돌렸을때 패스워드가 로그에 찍혀서, 마스킹 옵션 추가했습니다.
>

fix: mask-password option 추가

---

src/main/java/com/keeper/homepage/domain/member/entity/Member.java
src/main/resources/config/application.yml

> close: #113
`hibernate.default_batch_fetch_size`를 적용하였습니다. 사이즈는 의논한 후 우선 1000으로 잡았습니다.

Feature/default batch fetch size 적용

---

src/main/java/com/keeper/homepage/domain/library/application/BorrowManageService.kt
src/main/java/com/keeper/homepage/domain/library/dao/BookBorrowLogRepository.java
src/main/java/com/keeper/homepage/domain/library/dto/resp/BorrowLogResponse.kt
src/main/java/com/keeper/homepage/domain/library/entity/BookBorrowLog.java
src/test/java/com/keeper/homepage/domain/library/api/BookManageApiTestHelper.kt
src/test/java/com/keeper/homepage/domain/library/api/BorrowManageControllerTest.kt

> close: 없음.
소소한 수정사항입니당
해피 추석~~

Feature/대출 현황 가져오기 수정

---

src/main/java/com/keeper/homepage/domain/merit/api/MeritController.java
src/main/java/com/keeper/homepage/domain/merit/dao/MeritLogRepository.java
src/test/java/com/keeper/homepage/domain/merit/api/MeritControllerTest.java
src/test/java/com/keeper/homepage/domain/merit/application/MeritLogServiceTest.java

close : #367
1. GET 방식에 RequestBody가 담기지 않아 queryParam으로 수정했습니다.
2. 수정한 코드에 대한 테스트 코드를 추가했습니다.
3. 삭제하지 못한 주석을 삭제했습니다.
잘 부탁드리겠습니다~!
다들 추석 잘 보내세용!!

fix: RequestBody를 queryParam으로 수정 및 테스트 코드 추가

---

.github/workflows/deploy-development.yml

> close: 
> Github Action에서 실행되는 VM 시간대를 한국시간대로 수정
>

fix: GitHub Action timezone 변경

---

src/main/java/com/keeper/homepage/domain/member/api/MemberController.java
src/main/java/com/keeper/homepage/domain/member/application/MemberService.java
src/main/java/com/keeper/homepage/domain/member/dto/request/ChangePasswordRequest.java
src/test/java/com/keeper/homepage/domain/member/api/MemberControllerTest.java

> close: 없음.
비밀번호 변경시 현재 비밀번호 받도록 변경했습니당
굿~

fix: 비밀번호 변경시 현재 비밀번호 받도록 변경

---

src/main/java/com/keeper/homepage/domain/library/application/BookManageService.kt
src/main/java/com/keeper/homepage/domain/library/application/BookService.java
src/main/java/com/keeper/homepage/domain/library/dao/BookRepository.java
src/main/java/com/keeper/homepage/domain/library/entity/BookDepartment.java
src/test/java/com/keeper/homepage/domain/library/api/BookManageControllerTest.kt

> close: 없음
도서 관리 / 도서 목록에서 책이 이제 최신순으로 보입니다.
주말~~~~~~~~~~~

feat: 도서 최신순으로 정렬

---

src/main/java/com/keeper/homepage/global/config/security/filter/RefreshTokenFilter.java

fix: UNNOWN으로 수정

---

src/main/java/com/keeper/homepage/global/config/security/filter/RefreshTokenFilter.java

fix: filter chain 호출 문제 수정

---

build.gradle.kts
src/main/java/com/keeper/homepage/global/config/security/SecurityConfiguration.java
src/main/resources/config/application.yml

> close: https://github.com/KEEPER31337/Homepage-Infrastructure/pull/19#issue-2278570298
actuator 추가 & 기본 path 변경 (외부 크롤링 방지) `/metrics/prometheus` -> `/keeper-metrics/prometheus`
> 화이팅~

feat: actuator 추가
