KEEPER31337/Homepage-Back-R2

- src/main/java/com/keeper/homepage/domain/auth/api/test/AuthTestController.java
- src/main/java/com/keeper/homepage/global/config/security/annotation/LoginMember.java
- src/main/java/com/keeper/homepage/global/config/security/annotation/LoginMemberArgumentResolver.java
- src/main/java/com/keeper/homepage/global/config/web/WebMvcConfiguration.java
- src/test/java/com/keeper/homepage/domain/auth/api/AuthTestControllerTest.java
close: #43 
`@AuthId`로 로그인한 회원의 아이디를 가져오도록 되어 있었는데, 잘 사용하지 않을 것 같아 `@LoginMember` 어노테이션으로 변경 예정
AS-IS
```java
public void login(@AuthId long authId) {
Member loginMember = memberRepository.findById(authId).orElseThrow();
}
```
TO-BE
```java
public void login(@LoginMember Member loginMember) { }
```
남기고 싶은 내용을 설명해주세요.
> Feature/#43 @auth id 대신 @login member 사용

- build.gradle
- src/docs/auth/auth.adoc
- src/docs/keeper.adoc
- src/main/java/com/keeper/homepage/domain/auth/api/SignUpController.java
- src/main/java/com/keeper/homepage/domain/auth/application/EmailAuthService.java
- src/main/java/com/keeper/homepage/domain/auth/dao/redis/EmailAuthRedisRepository.java
- src/main/java/com/keeper/homepage/domain/auth/dto/request/EmailAuthRequest.java
- src/main/java/com/keeper/homepage/domain/auth/dto/response/EmailAuthResponse.java
- src/main/java/com/keeper/homepage/domain/auth/entity/redis/EmailAuthRedis.java
- src/main/java/com/keeper/homepage/global/config/security/SecurityConfiguration.java
- src/main/java/com/keeper/homepage/global/error/ErrorCode.java
- src/main/java/com/keeper/homepage/global/util/mail/MailUtil.java
- src/test/java/com/keeper/homepage/IntegrationTest.java
- src/test/java/com/keeper/homepage/domain/auth/api/SignUpControllerTest.java
- src/test/java/com/keeper/homepage/domain/auth/api/test/AuthTestControllerTest.java
- src/test/java/com/keeper/homepage/domain/auth/application/EmailAuthServiceTest.java
- src/test/java/com/keeper/homepage/global/util/mail/MailUtilTest.java
close: #31
이메일 인증 API 추가
**커밋 내역을 참고하시면 실제 기능 개발 전에 API 문서를 빠르게 뽑아내실 수 있습니다!**
1. **`Controller` & 필요한 껍데기 `Service` 구현 및 API 문서 작성** -> 
2. **급하다면 API 문서부터 프론트분에게 전달 후 다른 기능 개발 가능** -> 
3. **놓친 `Controller` TC 추가** -> 
4. **서비스 실제 로직 구현** -> 
5. **잘 동작할까 불안한 로직은 TC로 작성**
`application.yml`이 변경되었습니다.
> Feature/#31 이메일 인증 구현

- src/docs/auth/auth.adoc
- src/main/java/com/keeper/homepage/domain/auth/api/SignUpController.java
- src/main/java/com/keeper/homepage/domain/auth/application/CheckDuplicateService.java
- src/main/java/com/keeper/homepage/domain/auth/application/SignUpService.java
- src/main/java/com/keeper/homepage/domain/auth/dto/request/SignUpRequest.java
- src/main/java/com/keeper/homepage/domain/member/dao/MemberRepository.java
- src/main/java/com/keeper/homepage/domain/member/entity/Member.java
- src/main/java/com/keeper/homepage/domain/member/entity/embedded/Generation.java
- src/main/java/com/keeper/homepage/domain/member/entity/embedded/Profile.java
- src/main/java/com/keeper/homepage/global/config/password/PasswordConfiguration.java
- src/main/java/com/keeper/homepage/global/config/security/SecurityConfiguration.java
- src/main/java/com/keeper/homepage/global/error/ErrorCode.java
- src/main/java/com/keeper/homepage/global/error/ExceptionAdvice.java
- src/test/java/com/keeper/homepage/IntegrationTest.java
- src/test/java/com/keeper/homepage/domain/auth/api/SignUpControllerTest.java
- src/test/java/com/keeper/homepage/domain/auth/application/CheckDuplicateServiceTest.java
- src/test/java/com/keeper/homepage/domain/auth/application/SignUpServiceTest.java
- src/test/java/com/keeper/homepage/domain/member/MemberTestHelper.java
- src/test/java/com/keeper/homepage/domain/member/dao/MemberRepositoryTest.java
close: #30
- 회원가입 API 제작
- `로그인 아이디`, `이메일`, `학번` 중복 체크
- 회원가입시 인증코드 확인
- 비밀번호 저장 시 암호화
- 회원 생성 시 기본적으로 [일반회원], [정회원] 역할 부여
- 회원 생성 시 기수를 계산해서 적용
- `ExceptionAdvice`에 `RuntimeException`, `AccessDeniedException`, `HttpMessageNotReadableException` 추가
- `passwordEncoder` config 파일 분리
- 이관 전 비밀번호 암호화 방식도 적용하기 위해 레거시 코드 들어가있음 (언젠간 다른 사람들이 고쳐주길...)
- 에러 발생 시 리다이렉트 되는 `/error` URL에 권한 없어도 접근 가능하도록 변경
---
- **[test]** `objectMapper` `Autowired`로 주입하도록 변경
- **[test]** `@SpyBean`은 모킹 시 `when` 대신 `doReturn` 사용
다들 화이팅입니다!
> Feature/#30 회원가입 구현

- src/docs/about/about.adoc
- src/main/java/com/keeper/homepage/domain/about/api/StaticWriteController.java
- src/main/java/com/keeper/homepage/domain/about/application/StaticWriteService.java
- src/main/java/com/keeper/homepage/domain/about/converter/StaticWriteTitleTypeConverter.java
- src/main/java/com/keeper/homepage/domain/about/dao/StaticWriteContentRepository.java
- src/main/java/com/keeper/homepage/domain/about/dao/StaticWriteTitleRepository.java
- src/main/java/com/keeper/homepage/domain/about/dto/response/StaticWriteContentResponse.java
- src/main/java/com/keeper/homepage/domain/about/dto/response/StaticWriteSubTitleImageResponse.java
- src/main/java/com/keeper/homepage/domain/about/dto/response/StaticWriteTitleResponse.java
- src/main/java/com/keeper/homepage/domain/about/dto/response/StaticWriteTitleTypeResponse.java
- src/main/java/com/keeper/homepage/domain/about/entity/StaticWriteSubtitleImage.java
- src/main/java/com/keeper/homepage/domain/about/entity/StaticWriteTitle.java
- src/main/java/com/keeper/homepage/global/config/security/SecurityConfiguration.java
- src/main/java/com/keeper/homepage/global/error/ErrorCode.java
- src/test/java/com/keeper/homepage/IntegrationTest.java
- src/test/java/com/keeper/homepage/domain/about/StaticWriteTestHelper.java
- src/test/java/com/keeper/homepage/domain/about/api/StaticWriteControllerTest.java
- src/test/java/com/keeper/homepage/domain/about/application/StaticWriteServiceTest.java
- src/test/java/com/keeper/homepage/domain/about/dao/StaticWriteRepositoryTest.java
close: #35
페이지 블럭 타입의 리스트 조회, 타입으로 페이지 블럭 리스트 조회 API 개발을 했습니다.
간단한 조회 API 구현임에도, 이것 저것 생각할 게 많았습니다!
아직 부족한 점이 많네요! 코드리뷰 해주시면 감사합니다.
> Feature/#35 페이지블럭 리스트 조회 구현

- src/main/java/com/keeper/homepage/domain/auth/api/SignUpController.java
- src/main/java/com/keeper/homepage/domain/auth/application/CheckDuplicateService.java
- src/main/java/com/keeper/homepage/domain/auth/application/SignUpService.java
- src/main/java/com/keeper/homepage/domain/auth/dto/request/SignUpRequest.java
- src/main/java/com/keeper/homepage/domain/member/dao/MemberRepository.java
- src/main/java/com/keeper/homepage/domain/member/entity/Member.java
- src/main/java/com/keeper/homepage/domain/member/entity/embedded/EmailAddress.java
- src/main/java/com/keeper/homepage/domain/member/entity/embedded/LoginId.java
- src/main/java/com/keeper/homepage/domain/member/entity/embedded/Nickname.java
- src/main/java/com/keeper/homepage/domain/member/entity/embedded/Password.java
- src/main/java/com/keeper/homepage/domain/member/entity/embedded/Profile.java
- src/main/java/com/keeper/homepage/domain/member/entity/embedded/RealName.java
- src/main/java/com/keeper/homepage/domain/member/entity/embedded/StudentId.java
- src/main/java/com/keeper/homepage/global/config/password/PasswordFactory.java
- src/test/java/com/keeper/homepage/IntegrationTest.java
- src/test/java/com/keeper/homepage/domain/auth/api/SignUpControllerTest.java
- src/test/java/com/keeper/homepage/domain/auth/application/EmailAddressAuthServiceTest.java
- src/test/java/com/keeper/homepage/domain/auth/application/SignUpServiceTest.java
- src/test/java/com/keeper/homepage/domain/member/MemberTestHelper.java
- src/test/java/com/keeper/homepage/domain/member/dao/MemberRepositoryTest.java
close: #52
- `LoginId` Embedded 객체 생성
- `Password` Embedded 객체 생성
- `rawPassword`, `hashedPassword` 구분
- `Password` 객체엔 실제로 암호화 된 문자열만 가진다.
- 테스트 시 패스워드 암호화에 드는 시간을 아끼기 위해 `MockPasswordEncoder` 추가
- 값 객체에서도 `PasswordEncoder`를 쓰기 위해 `@Bean`으로 주입하지 않고 `PasswordEncoderFactory` 생성
- `EmailAddress` Embedded 객체 생성
- `RealName` Embedded 객체 생성
- `Nickname` Embedded 객체 생성
- `StudentId` Embedded 객체 생성
브랜치명 `feature/feature` ㅋㅋㅋ
> Feature/feature/#52 회원의 각 컬럼을 객체로 분리

- build.gradle.kts
없음.
API 문서가 보이지 않던 문제를 해결했습니다.
원인: build된 asciidoc html 파일들이 copy를 통해 static 폴더에 들어가야하는데 이게 적용되고 있지 않았습니다.
화이팅~!
> fix: API 문서 보이지 않던 문제 해결

- src/docs/asciidoc/keeper.adoc
- src/docs/asciidoc/study/study.adoc
- src/main/java/com/keeper/homepage/domain/member/entity/Member.java
- src/main/java/com/keeper/homepage/domain/post/dto/request/PostCreateRequest.java
- src/main/java/com/keeper/homepage/domain/post/dto/request/PostUpdateRequest.java
- src/main/java/com/keeper/homepage/domain/study/api/StudyController.java
- src/main/java/com/keeper/homepage/domain/study/application/StudyService.java
- src/main/java/com/keeper/homepage/domain/study/application/convenience/StudyFindService.java
- src/main/java/com/keeper/homepage/domain/study/dto/request/StudyCreateRequest.java
- src/main/java/com/keeper/homepage/domain/study/entity/Study.java
- src/main/java/com/keeper/homepage/global/error/ErrorCode.java
- src/test/java/com/keeper/homepage/IntegrationTest.java
- src/test/java/com/keeper/homepage/domain/post/api/PostControllerTest.java
- src/test/java/com/keeper/homepage/domain/study/api/StudyApiTestHelper.java
- src/test/java/com/keeper/homepage/domain/study/api/StudyControllerTest.java
close: #123
스터디 추가(생성), 삭제 기능을 구현했습니다!
스터디 제목, 내용 요청받을 때 최대 입력 가능 길이는 45, 100으로 일단 정해봤습니다! 기획서에 적어두겠습니다.
[스터디 기획서](https://enormous-button-c5d.notion.site/A1-A9-a9b13c9075f548c79f5f7408d113a2e9)
> Feature/스터디 추가 삭제 api 구현

- src/docs/asciidoc/game/baseball.adoc
- src/docs/asciidoc/game/game.adoc
- src/docs/asciidoc/keeper.adoc
- src/main/java/com/keeper/homepage/domain/game/api/GameController.kt
- src/main/java/com/keeper/homepage/domain/game/application/BaseballService.kt
- src/main/java/com/keeper/homepage/domain/game/application/GameFindService.kt
- src/main/java/com/keeper/homepage/domain/game/dao/GameRepository.java
- src/main/java/com/keeper/homepage/domain/game/dto/BaseballResult.kt
- src/main/java/com/keeper/homepage/domain/game/dto/req/BaseballGuessRequest.kt
- src/main/java/com/keeper/homepage/domain/game/dto/req/BaseballGuessResponse.kt
- src/main/java/com/keeper/homepage/domain/game/dto/req/BaseballStartRequest.kt
- src/main/java/com/keeper/homepage/domain/game/entity/Game.java
- src/main/java/com/keeper/homepage/domain/game/entity/embedded/Baseball.java
- src/main/java/com/keeper/homepage/domain/game/support/BaseballSupport.kt
- src/main/java/com/keeper/homepage/domain/member/entity/Member.java
- src/main/java/com/keeper/homepage/global/config/security/filter/RefreshTokenFilter.java
- src/main/java/com/keeper/homepage/global/error/ErrorCode.java
- src/main/java/com/keeper/homepage/global/util/redis/RedisUtil.java
- src/test/java/com/keeper/homepage/IntegrationTest.java
- src/test/java/com/keeper/homepage/domain/auth/api/SignOutControllerTest.java
- src/test/java/com/keeper/homepage/domain/auth/api/test/AuthTestControllerTest.java
- src/test/java/com/keeper/homepage/domain/game/GameTestHelper.java
- src/test/java/com/keeper/homepage/domain/game/api/GameApiTestHelper.kt
- src/test/java/com/keeper/homepage/domain/game/api/GameControllerTest.kt
- src/test/java/com/keeper/homepage/domain/game/support/BaseballSupportTest.kt
- src/test/java/com/keeper/homepage/global/util/redis/RedisUtilTest.java
close: #179
프론트 사이드 프로젝트인 야구 게임을 위한 API를 추가해봤습니다.
한 게임마다 그 게임이 끝나기 전까진 계속해서 상태를 유지해야 하는데, 
우리 서버가 stateless한 구조를 가지고 있어서 어쩔 수 없이 야구 게임에 대한 유저 세션 정보는 레디스로 관리하도록 했습니당.
> #179 야구 게임 백엔드 제작

- src/docs/asciidoc/keeper.adoc
- src/docs/asciidoc/seminar/seminar.adoc
close: 없음
api 문서의 html 파일이 안보이던 문제를 해결했습니다!
앞으로 문서 작성하실 때 요 부분 주의하시면 될 것 같아요 ㅎㅎ
> fix: api 문서 html 파일 안보이는 문제 해결

- src/docs/asciidoc/game/baseball.adoc
- src/main/java/com/keeper/homepage/domain/game/application/BaseballService.kt
- src/main/java/com/keeper/homepage/domain/game/dto/BaseballResult.kt
- src/main/java/com/keeper/homepage/domain/game/dto/req/BaseballGuessResponse.kt
- src/main/java/com/keeper/homepage/domain/game/support/BaseballSupport.kt
- src/test/java/com/keeper/homepage/domain/game/api/GameApiTestHelper.kt
- src/test/java/com/keeper/homepage/domain/game/api/GameControllerTest.kt
- src/test/java/com/keeper/homepage/domain/game/support/BaseballSupportTest.kt
close: #189
guess number를 기록하고 싶다는 요청이 있어서 추가
마지막 `guessNumber`만 저장하던 response에서 매 guess 마다 `guessNumber`를 함께 저장
```json
{
"guessNumber" : "1234",
"result" : [ {
"strike" : 2,
"ball" : 2
},
null,
{
"strike" : 1,
"ball" : 0
},
null,
null,
{
"strike" : 3,
"ball" : 0
} ],
"earnedPoint" : 0
}
```
```json
{
"result" : [ {
"guessNumber" : "1234",
"strike" : 2,
"ball" : 2
},
null,
{
"guessNumber" : "5678",
"strike" : 1,
"ball" : 0
},
null,
null,
{
"guessNumber" : "1239",
"strike" : 3,
"ball" : 0
} ],
"earnedPoint" : 0
}
```
response 스펙만 봐주세용, guessNumber와 strike, ball은 맞지 않을 수도 있습니다 ㅎㅎ...
> Feature/#189 baseball response 스펙 변경

- src/docs/asciidoc/library/book.adoc
- src/main/java/com/keeper/homepage/domain/library/api/BookController.java
- src/main/java/com/keeper/homepage/domain/library/application/BookService.java
- src/main/java/com/keeper/homepage/domain/library/dao/BookBorrowInfoRepository.java
- src/main/java/com/keeper/homepage/domain/library/dto/resp/BookBorrowResponse.java
- src/main/java/com/keeper/homepage/domain/library/dto/resp/BookResponse.java
- src/test/java/com/keeper/homepage/domain/library/api/BookApiTestHelper.java
- src/test/java/com/keeper/homepage/domain/library/api/BookControllerTest.java
- src/test/java/com/keeper/homepage/domain/library/application/BookServiceTest.java
- src/test/java/com/keeper/homepage/global/restdocs/RestDocsHelper.java
close: #194
close: #195
1. 도서 목록 조회 api의 응답으로 `canBorrow` 를 추가하였습니다!
요구사항을 보면 현재 책의 수량이 0인 경우 or 회원이 빌린 책의 개수가 5권일 경우는 false를 응답해야 합니다!
2. 도서 대여 목록 조회 api를 개발했습니다!
api는 위 처럼 사용됩니다! 회원이 빌린 책의 개수 정보도 이 api에서 얻을 수 있습니다!
> Feature/도서 대여 목록 조회 api

- src/docs/asciidoc/study/study.adoc
- src/main/java/com/keeper/homepage/domain/member/entity/Member.java
- src/main/java/com/keeper/homepage/domain/study/api/StudyController.java
- src/main/java/com/keeper/homepage/domain/study/application/StudyService.java
- src/main/java/com/keeper/homepage/domain/study/dao/StudyRepository.java
- src/main/java/com/keeper/homepage/domain/study/dto/request/StudyCreateRequest.java
- src/main/java/com/keeper/homepage/domain/study/dto/response/StudyDetailResponse.java
- src/main/java/com/keeper/homepage/domain/study/dto/response/StudyListResponse.java
- src/main/java/com/keeper/homepage/domain/study/dto/response/StudyResponse.java
- src/main/java/com/keeper/homepage/domain/study/entity/Study.java
- src/main/java/com/keeper/homepage/domain/study/entity/embedded/GitLink.java
- src/main/java/com/keeper/homepage/domain/study/entity/embedded/Link.java
- src/main/java/com/keeper/homepage/domain/study/entity/embedded/NoteLink.java
- src/test/java/com/keeper/homepage/domain/study/StudyTestHelper.java
- src/test/java/com/keeper/homepage/domain/study/api/StudyApiTestHelper.java
- src/test/java/com/keeper/homepage/domain/study/api/StudyControllerTest.java
close: #124
스터디 조회 api와 스터디 목록 조회 api를 개발했습니다.
- `memberNumber`(현재 스터디원 수) 컬럼 대신 DB에서 스터디원을 세는 방식을 채택했기 때문에 이 컬럼은 추후 삭제될 예정입니다.
- 스터디장이 스터디를 생성할 시 스터디원으로 추가되어야 할 것 같은데 이건 #176 에서 개발 후 검토하겠습니다~
- 스터디장 및 스터디원들의 이름은 실명으로 표기한다는 [기획서](https://enormous-button-c5d.notion.site/B1-B8-496c3d967d3b40ee8e166c9687065d5c) 내용에 따라서 구현했습니다!
> Feature/스터디 목록 조회 구현

- src/docs/asciidoc/game/baseball.adoc
- src/main/java/com/keeper/homepage/domain/game/api/GameController.kt
- src/main/java/com/keeper/homepage/domain/game/application/BaseballService.kt
- src/main/java/com/keeper/homepage/domain/game/dto/BaseballResult.kt
- src/main/java/com/keeper/homepage/domain/game/dto/req/BaseballGuessResponse.kt
- src/main/java/com/keeper/homepage/domain/game/dto/req/BaseballStartRequest.kt
- src/main/java/com/keeper/homepage/domain/game/dto/res/BaseballGuessResponse.kt
- src/main/java/com/keeper/homepage/domain/game/dto/res/BaseballResponse.kt
- src/main/java/com/keeper/homepage/domain/game/dto/res/GameInfoByMemberResponse.kt
- src/main/java/com/keeper/homepage/domain/game/entity/redis/BaseballResultEntity.kt
- src/main/java/com/keeper/homepage/domain/game/support/BaseballSupport.kt
- src/test/java/com/keeper/homepage/domain/game/api/GameApiTestHelper.kt
- src/test/java/com/keeper/homepage/domain/game/api/GameControllerTest.kt
- src/test/java/com/keeper/homepage/domain/game/support/BaseballSupportTest.kt
close: 없음
전체적인 코드 정리와 리팩토링을 진행했습니다.
1. redis 도메인 layer의 Entity와 프레젠테이션 layer의 dto를 분리했습니다.
2. 변수명 가독성 있게 변경
3. 한 게임이 끝나면 얻을 수 있는 포인트를 계산하던 방식 -> 매 라운드마다 얻을 수 있는 포인트를 계산할 수 있도록 변경
1. 베팅 포인트 제한 설정 (min 10, max: 1000)
2. 야구게임의 하드코딩된 정보들(추측할 숫자 길이, 라운드 수, 최대 베팅 포인트, 최소 베팅 포인트)을 가져오는 API 추가
3. API로 내려가는 필드명 변경
- earnedPoint -> earnablePoints
- 게임 결과를 의미하는 result -> results
굉장히 끔찍한 코드입니다 ㅠㅠ 조금 더 잘했으면 좋았을텐데...
**PR 머지 전에 프론트에 해당 사항 공유하기~!**
> 야구게임 추가요청사항 반영

- src/docs/asciidoc/member/member.adoc
- src/docs/asciidoc/study/study.adoc
- src/main/java/com/keeper/homepage/domain/member/api/MemberController.java
- src/main/java/com/keeper/homepage/domain/member/application/MemberService.java
- src/main/java/com/keeper/homepage/domain/member/application/convenience/MemberFindService.java
- src/main/java/com/keeper/homepage/domain/member/dao/MemberRepository.java
- src/main/java/com/keeper/homepage/domain/member/dto/response/MemberResponse.java
- src/main/java/com/keeper/homepage/domain/study/application/StudyService.java
- src/main/java/com/keeper/homepage/domain/study/dto/response/StudyDetailResponse.java
- src/main/java/com/keeper/homepage/domain/study/entity/Study.java
- src/main/java/com/keeper/homepage/domain/study/entity/embedded/Link.java
- src/main/java/com/keeper/homepage/global/error/ErrorCode.java
- src/test/java/com/keeper/homepage/IntegrationTest.java
- src/test/java/com/keeper/homepage/domain/member/api/MemberControllerTest.java
- src/test/java/com/keeper/homepage/domain/study/api/StudyControllerTest.java
- src/test/java/com/keeper/homepage/domain/study/application/StudyServiceTest.java
close: #125
1. 스터디 로직 수정
- 스터디 개설 시 api 호출한 사람(스터디장)은 스터디원으로 등록됩니다.
- 스터디 링크는 1개 이상이어야 합니다.
- 스터디장은 스터디원 탈퇴가 불가합니다.
_[기획서](https://www.notion.so/B1-B8-496c3d967d3b40ee8e166c9687065d5c?pvs=4)를 꼼꼼히 보자_
2. 회원 목록 조회(검색) 기능 구현
- 스터디원을 추가할 때 필요한 회원 목록 조회 기능을 구현했습니다!
- 추후 확장 가능성이 있는 api 인 것 같습니다! (여러 곳에서 쓰일 것 같다...!)
- `ResponseEntity<List<~>>`로 전달해도 필드가 하나면 상관 없다고 하더라구요!
`MemberFindService` 쪽 괜찮은지 봐주세요!
> Feature/회원 조회(검색) 기능구현

- src/docs/asciidoc/library/book-manage.adoc
- src/main/java/com/keeper/homepage/domain/library/api/BookManageController.kt
- src/main/java/com/keeper/homepage/domain/library/application/BookManageService.kt
- src/main/java/com/keeper/homepage/domain/library/dto/resp/BookDetailResponse.kt
- src/test/java/com/keeper/homepage/domain/library/api/BookManageApiTestHelper.kt
- src/test/java/com/keeper/homepage/domain/library/api/BookManageControllerTest.kt
- src/test/java/com/keeper/homepage/domain/library/api/BorrowManageControllerTest.kt
close: 없음
관리자 도서 목록 조회 API 추가
남기고 싶은 내용을 설명해주세요.
> feat: 관리자 도서 목록 조회 API 추가

- src/main/java/com/keeper/homepage/domain/comment/dto/response/CommentResponse.java
- src/test/java/com/keeper/homepage/domain/comment/api/CommentControllerTest.java
close: #없음
빠져 있던 `commentId`를 응답으로 추가했습니다.
> fix: 댓글 목록 조회 api 스펙에 commentId 추가

- src/docs/asciidoc/attendance/attendance.adoc
- src/docs/asciidoc/keeper.adoc
- src/docs/asciidoc/post/post.adoc
- src/main/java/com/keeper/homepage/domain/attendance/api/AttendanceController.java
- src/main/java/com/keeper/homepage/domain/attendance/application/AttendanceService.java
- src/main/java/com/keeper/homepage/domain/attendance/application/BonusPoint.java
- src/main/java/com/keeper/homepage/domain/attendance/application/RankPoint.java
- src/main/java/com/keeper/homepage/domain/attendance/dao/AttendanceRepository.java
- src/main/java/com/keeper/homepage/domain/attendance/dto/response/AttendanceResponse.java
- src/main/java/com/keeper/homepage/domain/attendance/entity/Attendance.java
- src/main/java/com/keeper/homepage/domain/member/application/convenience/MemberFindService.java
- src/main/java/com/keeper/homepage/domain/member/dao/MemberRepository.java
- src/main/java/com/keeper/homepage/domain/member/entity/Member.java
- src/main/java/com/keeper/homepage/domain/point/application/PointLogService.java
- src/main/java/com/keeper/homepage/domain/point/dao/PointLogRepository.java
- src/main/java/com/keeper/homepage/domain/point/entity/PointLog.java
- src/main/java/com/keeper/homepage/global/error/ErrorCode.java
- src/main/java/com/keeper/homepage/global/util/redis/RedisUtil.java
- src/test/java/com/keeper/homepage/IntegrationTest.java
- src/test/java/com/keeper/homepage/domain/attendance/api/AttendanceControllerTest.java
- src/test/java/com/keeper/homepage/domain/attendance/application/AttendanceServiceTest.java
close: #212
close: #173
close: #172
close: #16
- 출석 기능 구현
- `PointLog` `Entity`, `Repository` 개발
- `Rank`는 `Redis`에서 계산하도록 하였습니다! (이전 홈페이지 코드 참고했습니다!)
- 당일의 출석 랭킹 조회 구현
- 연속 출석 랭킹 조회 구현
`Redis`를 처음으로 직접 사용해봤습니다...! 이것 저것 다른 것도 `Redis`에 띄우면 좋겠다는 생각이 듭니다!
> Feature/출석 + 출석 랭킹 기능 구현

- src/main/java/com/keeper/homepage/domain/post/application/PostService.java
- src/main/java/com/keeper/homepage/domain/post/dao/PostRepository.java
- src/main/java/com/keeper/homepage/domain/post/dto/response/AdjacentPostResponse.java
- src/main/java/com/keeper/homepage/domain/post/dto/response/PostDetailResponse.java
- src/test/java/com/keeper/homepage/domain/post/api/PostControllerTest.java
- src/test/java/com/keeper/homepage/domain/post/application/PostServiceTest.java
close: #없음
요구사항에 맞게 게시글 조회 api의 응답 필드에 이전, 다음 게시글 정보를 추가했습니다.
---
게시글 쪽 테스트 코드 엉망이네요... 일단 미루고 추후 리팩토링 하겠습니다 😂
> Feature/게시글 조회 api 스펙 변경

- src/main/java/com/keeper/homepage/domain/member/entity/job/MemberJob.java
- src/main/java/com/keeper/homepage/domain/study/dto/request/StudyCreateRequest.java
- src/main/java/com/keeper/homepage/domain/study/dto/request/StudyUpdateRequest.java
- src/main/java/com/keeper/homepage/domain/study/dto/response/StudyDetailResponse.java
- src/main/java/com/keeper/homepage/domain/study/entity/Study.java
- src/main/java/com/keeper/homepage/domain/study/entity/embedded/Link.java
- src/main/java/com/keeper/homepage/domain/study/entity/embedded/NotionLink.java
- src/test/java/com/keeper/homepage/domain/study/StudyTestHelper.java
- src/test/java/com/keeper/homepage/domain/study/api/StudyControllerTest.java
close: #202
close: #226
20230716일자 DB 업데이트 사항을 백엔드에 적용했습니다.
- `study`
- `note_link` 컬럼명을 `notion_link`로 변경했습니다. (기획 상 노션 링크만 받게되어 그렇습니다.)
- `member_job`
- `ROLE_전산관리자` 직책을 `ROLE_FRONT_전산관리자` , `ROLE_BACK_전산관리자` 직책으로 나눴습니다. 이제 두 직책을 구별할 수 있습니다.
> Feature/study + member_job db 변경 적용

- src/docs/asciidoc/library/book-manage.adoc
- src/main/java/com/keeper/homepage/domain/library/api/BookManageController.kt
- src/main/java/com/keeper/homepage/domain/library/dto/req/BookRequest.kt
- src/test/java/com/keeper/homepage/domain/library/api/BookManageApiTestHelper.kt
- src/test/java/com/keeper/homepage/domain/library/api/BookManageControllerTest.kt
[슬랙 호출 🥲](https://keepernewhome-5o41027.slack.com/archives/C04LNV3V604/p1690089269942479?thread_ts=1690041572.996339&cid=C04LNV3V604)
`content-type`이 `multipart/form-data`인 API의 경우 url query parameter로 request를 보냈었는데, 이렇게 되면 [url 길이 제한(2038자](https://support.microsoft.com/ko-kr/topic/internet-explorer%EC%9D%98-%EC%B5%9C%EB%8C%80-url-%EA%B8%B8%EC%9D%B4%EB%8A%94-2-083%EC%9E%90%EC%9E%85%EB%8B%88%EB%8B%A4-174e7c8a-6666-f4e0-6fd6-908b53c12246) 때문에 문제가 생길 수 있어서 request body로 데이터를 받게끔 변경함.
월요일 좋아~ 😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭
> 파일 포함 데이터 전달 시 requestBody로 전달하도록 변경

- src/main/java/com/keeper/homepage/domain/auth/api/SignInController.java
- src/main/java/com/keeper/homepage/domain/auth/application/SignInService.java
- src/main/java/com/keeper/homepage/domain/auth/dto/response/SignInResponse.java
- src/test/java/com/keeper/homepage/domain/auth/api/SignInControllerTest.java
> close: 없음.
원래 로그인 시 역할만 전달했었는데, 회원 상세 정보를 모두 보내주도록 변경했습니다.
PR 머지시 프론트에 [로그인 API](https://api.dev.keeper.or.kr/docs/auth/auth.html#_%EB%A1%9C%EA%B7%B8%EC%9D%B8) 전달
벌써 월요일이라니...
> feat: 로그인 시 회원 상세 정보 전달하도록 변경

- src/main/java/com/keeper/homepage/domain/auth/application/AuthCookieService.java
없음.
로그인이 자꾸 ACCESS TOKEN 만료시간만큼 지나면 풀린다는 이슈가 있어서 확인해봄.
`refresh token`이 있는데 동작을 하고 있지 않길래 봤더니 `access token 쿠키` 만료 시간이 `access token` 만료시간(1시간)과 같았음.
그래서 1시간이 지나면 **쿠키가 아예 사라져버려서** 백엔드에서 이상하게 동작하는게 원인이었음.
`access token`의 토큰 만료 시간은 1시간으로 하되, 쿠키 만료시간은 `refresh token`과 같은 2주로 변경.
화요일은 쉬는날~
> fix: ACCESS TOKEN 쿠키 만료시간은 REFRESH TOKEN과 동일하게 변경

- src/main/java/com/keeper/homepage/domain/attendance/application/AttendanceService.java
- src/main/java/com/keeper/homepage/domain/game/application/BaseballService.kt
- src/main/java/com/keeper/homepage/domain/member/entity/Member.java
- src/main/java/com/keeper/homepage/domain/point/application/PointLogService.java
- src/main/java/com/keeper/homepage/domain/point/entity/PointLog.java
- src/main/java/com/keeper/homepage/domain/post/application/PostService.java
- src/test/java/com/keeper/homepage/domain/game/api/GameControllerTest.kt
> close: #없음
기획서 보니까 족보 열람할때 차감한 포인트에 대한 로그도 남겨줘야겠더라구요! 해당 작업 수행했습니다.
> feat: 족보 열람시 차감된 포인트 로그 생성 코드 추가

- src/main/java/com/keeper/homepage/domain/auth/api/SignInController.java
- src/main/java/com/keeper/homepage/domain/auth/application/AuthCookieService.java
- src/main/java/com/keeper/homepage/domain/auth/application/SignInService.java
- src/main/java/com/keeper/homepage/global/config/security/JwtTokenProvider.java
- src/main/java/com/keeper/homepage/global/config/security/filter/RefreshTokenFilter.java
- src/test/java/com/keeper/homepage/domain/auth/api/SignInControllerTest.java
- src/test/java/com/keeper/homepage/domain/auth/api/test/AuthTestControllerTest.java
close: 없음
사용자가 다른 디바이스에서 로그인하면 기존 refreshToken이 무효화되는 문제를 해결하고자 userAgent를 사용하도록 하였습니다.
이제 refreshToken을 redis에 저장할 때 Id + userAgent를 key로 사용합니다.
[User Agent란?](https://developer.mozilla.org/ko/docs/Glossary/User_agent)
직장인도 방학... ㅠㅠ
> fix: refreshToken redis 저장 시 Id + userAgent 사용

- src/docs/asciidoc/study/study.adoc
- src/main/java/com/keeper/homepage/domain/member/entity/Member.java
- src/main/java/com/keeper/homepage/domain/study/api/StudyController.java
- src/main/java/com/keeper/homepage/domain/study/application/StudyService.java
- src/main/java/com/keeper/homepage/domain/study/dao/StudyHasMemberRepository.java
- src/main/java/com/keeper/homepage/domain/study/dto/request/StudyCreateRequest.java
- src/main/java/com/keeper/homepage/domain/study/dto/request/StudyUpdateRequest.java
- src/main/java/com/keeper/homepage/domain/study/entity/Study.java
- src/test/java/com/keeper/homepage/domain/study/api/StudyControllerTest.java
- src/test/java/com/keeper/homepage/domain/study/application/StudyServiceTest.java
- src/test/java/com/keeper/homepage/domain/study/dao/StudyHasMemberRepositoryTest.java
> issue: #323
프론트 개발자님이 스터디원 추가, 삭제 api를 따로 따로 적용하기가 처리할 부분이 많다고 하여, 스터디 생성과 수정 api에서 스터디원까지 함께 업데이트 하도록 방식을 바꾸었습니다.
- 스터디 수정시 변경되지 않는 회원은 불필요하게 삭제, 추가 과정을 거쳐야 하는 데 크리티컬하지 않을 것 같아서 요청을 수락하였습니다. 괜찮을 지 검토 부탁드립니다!
바꾸는 김에, 이슈 #323 을 고려하여 cascadeType.REMOVE와 orphanRemoval을 부분적으로 제거해보았습니다. 오히려 명시적으로 제거해주는 코드가 있어서 가독성 측면에서도 나쁘지 않은 것 같은데 피드백 부탁드립니다!
로직이 변경되어서 기존의 api와 테스트를 삭제하였는데 뭔가 아깝네요...ㅠㅠ
> Feature/스터디 변경 요구사항

- src/main/java/com/keeper/homepage/domain/post/dao/PostRepository.java
> close: 없음.
@shkisme SQL에서 `OR`연산은 `AND`연산보다 우선순위가 밀리므로 아래의 기존 쿼리는 `content`에 데이터만 있다면 카테고리를 무시하고 데이터를 가져오는 쿼리였습니다.
```sql
WHERE p.category = :category # false (카테고리가 일치하지 않더라도)
AND p.isNotice = false 
AND p.isTemp = false 
AND LOWER(p.title) LIKE LOWER(concat('%', :search, '%')) 
OR LOWER(p.content) LIKE LOWER(concat('%', :search, '%')) # true (이게 true면 다 가져옴)
```
수정된 쿼리는 아래와 같습니다.
```sql
WHERE p.category = :category
AND p.isNotice = false 
AND p.isTemp = false 
AND (LOWER(p.title) LIKE LOWER(concat('%', :search, '%')) 
OR LOWER(p.content) LIKE LOWER(concat('%', :search, '%'))) # 괄호로 묶음
```
월요일 좋아....
> fix: 게시글 제목 + 내용 검색 시 카테고리 상관없이 검색하던 문제 수정

- src/main/java/com/keeper/homepage/global/config/p6spy/PrettySqlFormat.java
- src/main/java/com/keeper/homepage/global/config/password/PasswordFactory.java
- src/main/java/com/keeper/homepage/global/error/ExceptionAdvice.java
- src/test/java/com/keeper/homepage/domain/auth/application/EmailAddressAuthServiceTest.java
> close: #118 
> 이현님이 올려주신 이슈 내용대로 String.format을 JDK15에 추가된 formatted으로 변경했습니다.
```java
String a = String.format("keeper: %s", "keeper");
String b = "keeper: %s".formatted("keeper");
```
>
> refactor: String.format에서 formatted로 변경하기 #118

- src/docs/asciidoc/merit/merit.adoc
- src/main/java/com/keeper/homepage/domain/merit/api/MeritController.java
- src/main/java/com/keeper/homepage/domain/merit/application/MeritLogService.java
- src/main/java/com/keeper/homepage/domain/merit/dao/MeritLogRepository.java
- src/main/java/com/keeper/homepage/domain/merit/dto/response/MeritLogsGroupByMemberResponse.java
- src/main/java/com/keeper/homepage/domain/merit/entity/MeritLog.java
- src/main/java/com/keeper/homepage/domain/point/api/PointController.java
- src/test/java/com/keeper/homepage/domain/merit/api/MeritApiTestHelper.java
- src/test/java/com/keeper/homepage/domain/merit/api/MeritControllerTest.java
- src/test/java/com/keeper/homepage/domain/merit/application/MeritLogServiceTest.java
- src/test/java/com/keeper/homepage/domain/merit/dao/MeritLogRepositoryTest.java
close: #343
회원 통계 상벌점 목록 조회 기능을 추가했습니다!
예전에는 merit와 demerit 컬럼이 있었는데 현재는 merit로 통합이 됐습니다. 그래서 상점만 받으면 될 줄 알았는데 상벌점 구분해서 넘겨달라고 하셨습니다! 
집계함수를 사용해서 완성은 했지만 아직 데이터베이스 수업도 안듣고 이번에 처음 사용해서 조금 찝찝하네요... 더 좋은 방법이 있을까요?.?
+) 쿼리DSL 강의를 들어봤는데 너무 좋은 거 같습니다..! 이번 회원 통계 목록 조회 기능이랑 상벌점 사유 수정 중에 사유 이름을 변경하지 않으면 이미 존재하는 사유로 판단되어 수정이 안 되는 이슈에도 적용하면 좋을 거 같다라는 생각이 드네요..! 
혹시 R2 프로젝트에 DSL 도입 안 될까요..?? 👀
> Feature/상벌점 회원 통계 목록 조회 기능 추가

- src/docs/asciidoc/post/post.adoc
- src/main/java/com/keeper/homepage/domain/post/application/PostService.java
- src/main/java/com/keeper/homepage/domain/post/dto/response/PostDetailResponse.java
- src/main/java/com/keeper/homepage/domain/post/dto/response/PostResponse.java
- src/test/java/com/keeper/homepage/domain/post/api/PostApiTestHelper.java
- src/test/java/com/keeper/homepage/domain/post/api/PostControllerTest.java
- src/test/java/com/keeper/homepage/domain/post/application/PostServiceTest.java
> close: #없음
- 시험 게시판 목록 조회 응답으로 `fileCount` (첨부파일 개수) 추가
- 시험 게시글 조회 응답으로 `isRead` (열람 여부) 추가
- 본인 게시글의 첨부파일 조회 시에는 포인트 차감되지 않도록 수정
시험 게시글을 제외한 다른 카테고리 게시글의 `fileCount`, `isRead`는 null로 보냅니다.
> Feature/족보 게시글 관련 처리

- src/docs/asciidoc/member/member.adoc
- src/main/java/com/keeper/homepage/domain/member/api/MemberController.java
- src/main/java/com/keeper/homepage/domain/member/application/MemberProfileService.java
- src/main/java/com/keeper/homepage/domain/member/application/MemberService.java
- src/main/java/com/keeper/homepage/domain/member/dto/request/DeleteMemberRequest.java
- src/main/java/com/keeper/homepage/domain/member/entity/Member.java
- src/main/java/com/keeper/homepage/domain/member/entity/embedded/Profile.java
- src/main/java/com/keeper/homepage/global/error/ErrorCode.java
- src/test/java/com/keeper/homepage/domain/member/api/MemberControllerTest.java
- src/test/java/com/keeper/homepage/domain/member/application/MemberServiceTest.java
close: #64
회원 탈퇴 기능을 만들었습니다.
초반 커밋을 보시면 회원 아이디, 비밀번호, 이메일 등등 전부 다 탈퇴, 삭제 등으로 마킹을 했었는데 의견을 나눈 결과 is_delete를 업데이트하고 회원 이름만 탈퇴회원으로 마킹하도록 했습니다..!! (게시글에 탈퇴회원으로 표기되게끔) 다른 분들의 의견도 궁금합니다~ 어떻게 해야 할까요 ?.?
+) 9월 17일 수정
Column 값으로 사람을 특정할 수 있는 정보(login_id, email, pw, real_name, birth, student_id, thumbnail)만 마킹하도록 결정했습니다!
마킹 테스트를 할 때 네이티브 쿼리를 사용한 이유는 @Where 어노테이션이 적용되어서 계속 예외가 발생해서 그렇습니다! 이 테스트에서 JPQL도 사용해봤는데 @Where 어노테이션이 적용되서 아직까지는 문제 없는 것 같습니다!!
> Feature/회원 탈퇴 기능

- src/docs/asciidoc/attendance/attendance.adoc
- src/main/java/com/keeper/homepage/domain/attendance/api/AttendanceController.java
- src/main/java/com/keeper/homepage/domain/attendance/application/AttendanceService.java
- src/main/java/com/keeper/homepage/domain/post/application/PostService.java
- src/main/java/com/keeper/homepage/domain/post/entity/Post.java
- src/main/java/com/keeper/homepage/global/config/interceptor/AttendanceInterceptor.java
- src/main/java/com/keeper/homepage/global/config/web/WebMvcConfiguration.java
- src/main/java/com/keeper/homepage/global/error/ErrorCode.java
- src/test/java/com/keeper/homepage/domain/attendance/api/AttendanceControllerTest.java
- src/test/java/com/keeper/homepage/domain/attendance/application/AttendanceServiceTest.java
> close: #348
회원 출석에 관한 처리를 백엔드에서 하도록 추가 구현하였습니다. `Interceptor`를 활용하여 구현했는데 잘 구현한 건지 확인 부탁드립니당..!
참고로 출석은 `메인`, `회원`, `출석` 도메인의 api 요청에 대해서만 출석 처리를 하는 것으로 의논하였습니다.
3-2 개강을 했습니당... 🫠
> Feature/출석 백엔드에서 처리

- src/main/java/com/keeper/homepage/domain/member/api/MemberController.java
- src/main/java/com/keeper/homepage/domain/member/application/MemberProfileService.java
- src/main/java/com/keeper/homepage/domain/member/application/MemberService.java
- src/main/java/com/keeper/homepage/domain/member/dao/MemberRepository.java
- src/main/java/com/keeper/homepage/domain/member/dao/friend/FriendRepository.java
- src/main/java/com/keeper/homepage/domain/member/dto/response/profile/MemberFriendResponse.java
- src/main/java/com/keeper/homepage/domain/member/dto/response/profile/MemberProfileResponse.java
- src/main/java/com/keeper/homepage/domain/member/entity/Member.java
- src/main/java/com/keeper/homepage/domain/member/entity/embedded/Profile.java
- src/test/java/com/keeper/homepage/domain/member/api/MemberApiTestHelper.java
- src/test/java/com/keeper/homepage/domain/member/api/MemberControllerTest.java
- src/test/java/com/keeper/homepage/domain/member/application/MemberProfileServiceTest.java
- src/test/java/com/keeper/homepage/domain/member/application/MemberServiceTest.java
1. 프로필 조회 시 발생하는 N+1 문제를 해결하였습니다. 영한킴 강의를 참고했고 강의 기준으로 V3.1 버전으로 맞췄습니다. 여러 가지 실험을 해봤는데 컬렉션 참고하는 경우는 @BatchSize를 거는게 가장 빠른 것으로 확인했습니다. (V4, V5 코드도 작성해보고 싶어 몇몇 코드에 주석이 되어있습니다. 머지될 때는 다 삭제한 후 깔끔하게 올리도록 하겠습니다~!)
2. 프로필 조회 API 응답 값에 회원의 학번이 추가 되었습니다. 예전 민감한 정보라 삭제했었는데 프론트 요청으로 본인 조회일 때만 본인 학번 정보를 포함해서 보내주는 방식으로 변경하였습니다. 본인이 아닐 경우 "default" 문자열로 띄워주기로 결정했습니다.
3. 프론트 요청으로 이메일 인증 코드 발송 API 응답으로 인증 코드 유효 시간 300초를 보내도록 수정했습니다.
+)
4. 이메일 변경 API가 정상적으로 작동되지 않는 것을 확인했고 수정 완료했습니다.
잘 부탁 드리겠습니다~! 감사합니다..!
> Feature/회원 프로필 조회 수정

- src/docs/asciidoc/merit/merit.adoc
- src/main/java/com/keeper/homepage/domain/merit/api/MeritController.java
- src/main/java/com/keeper/homepage/domain/merit/application/MeritLogService.java
- src/main/java/com/keeper/homepage/domain/merit/application/MeritTypeService.java
- src/main/java/com/keeper/homepage/domain/merit/dao/MeritLogRepository.java
- src/main/java/com/keeper/homepage/domain/merit/dto/request/AddMeritTypeRequest.java
- src/main/java/com/keeper/homepage/domain/merit/dto/request/SearchMeritLogListRequest.java
- src/main/java/com/keeper/homepage/domain/merit/dto/request/UpdateMeritTypeRequest.java
- src/main/java/com/keeper/homepage/domain/merit/dto/response/MeritLogsGroupByMemberResponse.java
- src/main/java/com/keeper/homepage/domain/merit/dto/response/MeritTypeResponse.java
- src/main/java/com/keeper/homepage/domain/merit/dto/response/SearchMemberMeritLogResponse.java
- src/main/java/com/keeper/homepage/domain/merit/dto/response/SearchMeritLogListResponse.java
- src/main/java/com/keeper/homepage/domain/merit/entity/MeritType.java
- src/main/java/com/keeper/homepage/global/error/ErrorCode.java
- src/test/java/com/keeper/homepage/domain/merit/MeritTypeHelper.java
- src/test/java/com/keeper/homepage/domain/merit/api/MeritApiTestHelper.java
- src/test/java/com/keeper/homepage/domain/merit/api/MeritControllerTest.java
- src/test/java/com/keeper/homepage/domain/merit/application/MeritLogServiceTest.java
- src/test/java/com/keeper/homepage/domain/merit/application/MeritTypeServiceTest.java
- src/test/java/com/keeper/homepage/domain/merit/dao/MeritLogRepositoryTest.java
> close: #354
1. 상벌점 로그 조회 API에서 MERIT, DEMERIT, ALL을 클라이언트에게 입력 받아서 상점/벌점/전체로 조회되도록 필터링을 추가했습니다.
2. 회원별 상벌점 로그 조회 API에서 ASC, DESC(기본값)을 클라이언트에게 입력 받아서 정렬하는 기능을 추가했습니다.
3. 상벌점 내역 삭제 기능을 추가했습니다.
4. 상벌점 타입 수정 API에서 사유 이름을 변경하지 않으면 이미 존재하는 사유로 판단되는 버그를 수정했습니다.
4번 버그를 수정하는데 더 좋은 방법이 있을까요?~?
잘 부탁드리겠습니다..!!!
> Feature/상벌점 기능 추가 및 버그 수정

- src/main/java/com/keeper/homepage/global/config/interceptor/AttendanceInterceptor.java
> close: #359
- 53ddcda55e4ae3ffb0989975a2b1db51fb5b7ea8 에서 redis 값 만료시간 설정이 잘못되어 있었던 문제를 수정했습니다.
- eeaf5bddfb0f0108c98ce83730e4b281353b1952 에서 SessionCallback 인터페이스를 활용하여 문제 발생 시 Redis에서도 Transaction이 동작하도록 수정하였습니다. #359 문제는 프론트 페이지(ex. 메인페이지)에서 여러개의 api를 동시에 호출하여, 요청이 스레드에서 병렬로 돌아서 db 단에서 trigger 걸어둔 출석 중복 저장 에러가 발생했는데, redis의 값은 롤백이 되지 않아 발생한 문제로 추측합니다.
- ce11237183a9bad6b3615fcc94034e6aa7e5601d 에서 클라이언트에게 출석 중복 저장 에러(500)을 던져주지 않게 catch 하였습니다.
추석때 작업 힘들 것 같아 바로 머지하겠습니다! 추후 피드백 환영입니다!
> fix: 출석 순위 버그 수정

- build.gradle.kts
> close: #363
In 절에 BatchSize 만큼의 중복된 ID가 바인딩되는 문제를 해결했습니다.
In 절에 BatchSize 만큼의 중복된 ID가 바인딩되는 문제는 하이버네이트 6.1.x 버전에서 있었던 버그였습니다. ([참고링크](https://ttl-blog.tistory.com/1202)) 이 버그는 하이버네이트 6.2.x 버전에서 수정되었는데, 현재 사용하고 있는 스프링 부트 3.0.1 버전에서는 default로 하이버네이트 버전 6.1.x 버전을 사용하고 있습니다.
처음에는 하이버네이트 6.2.0 버전으로 업데이트 하면 해결되겠거니 했는데, 의존성 관련 문제인지 어플리케이션이 실행되지 않았습니다. 그래서 스프링 부트 3.0.2 버전으로 업데이트를 해보았더니 문제가 해결되었습니다! (스프링 부트 3.0.2 버전도 하이버네이트 버전을 명시해주지 않으면 6.1.x 버전을 default로 사용하기에 하이버네이트 버전도 명시해주었습니다.)
버전 업데이트 문제 없을 지 확인해주시면 감사하겠습니다! 🙇
해결에 있어 문제 원인 파악에 도움 주신 @02ggang9 님 감사합니다~~👍
> In 절에 BatchSize 만큼의 중복된 ID가 바인딩되는 문제 해결

- src/main/java/com/keeper/homepage/domain/library/application/BorrowManageService.kt
- src/test/java/com/keeper/homepage/domain/library/api/BorrowManageControllerTest.kt
없음.
https://keepernewhome-5o41027.slack.com/archives/C04MA6U2K96/p1697026769781889
대출 신청 취소시엔 `borrowInfo`가 삭제되고 있었는데, 관리자 페이지에서 대출 신청을 반려했을 땐 `borrowInfo`가 삭제되지 않아 생기는 문제를 해결했습니다.
원래 `대출반려`로 하기로 했던 것 같은데 `borrowLog`가 생기면서 굳이 `대출반려`로 남겨놓을 필요 없을 것 같아서 제거합니다. 나중에 시간날때 `대출반려` enum도 제거하면 좋을 것 같아요.
오랜만입니당 😄
> feat: 대출 반려시 대출 정보 row 제거

- src/main/java/com/keeper/homepage/domain/auth/application/AuthCookieService.java
- src/main/java/com/keeper/homepage/domain/auth/application/SignOutService.java
- src/main/java/com/keeper/homepage/global/config/security/filter/RefreshTokenFilter.java
- src/test/java/com/keeper/homepage/domain/auth/api/SignOutControllerTest.java
> close: 없음
로그아웃 시에 정상적이라면 Response는 없이 204가 내려가야 함.
그런데 로그아웃을 누를 당시에 accessToken과 refreshToken 모두 만료됐을 경우 204 대신 401이 내려가게 됨.
지금은 401이 내려가도 쿠키가 지워지지 않아서 로그아웃이 안되고 있었어서 401이 내려가는 상황이면 항상 쿠키를 지우게끔 수정
오랜만에 코딩하니까 재밌네요~
@02ggang9 인증 부분 인수인계 해드릴까요...? ㅎㅎ 바빠서 유지보수 대응할 시간이 부족하네용
> fix: status 401이 내려갈 때 쿠키 모두 삭제

- src/main/java/com/keeper/homepage/global/config/security/filter/RefreshTokenFilter.java
https://github.com/KEEPER31337/Homepage-Back-R2/issues/403
두 JWT 토큰이 비었을 때는 빈 토큰 값을 주입하지 않도록 수정했습니다.
조금 급한 문제인 것 같아서 막 짯네요..! 나중에 수정하도록 하겠습니다
> fix: JWT 토큰이 둘 다 비었을 때 빈 토큰 주입을 하지 않도록 수정

- src/test/java/com/keeper/homepage/domain/auth/api/test/AuthTestControllerTest.java
- src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
https://github.com/KEEPER31337/Homepage-Back-R2/issues/398
모킹을 통해서 ACCESS_TOKEN의 expiredMillis를 0으로 설정했습니다.
이를 통해서 SECRET 환경 변수의 값이 달라져도 그에 맞는 토큰 값을 생성할 수 있습니다. 또, accessToken과 refreshToken의 PK 값이 맞지 않는 부분도 수정했습니다.
도무지 모킹을 하지 않고는 issue의 문제를 해결할 방법이 떠오르지 않네요..!! ㅠㅠ 또, ReadME에 Quick Start를 만들 때 .env에 어떤 키가 들어가는지 정도는 노출을 해야 하는데 이 부분은 보안상으로 문제가 없을지 다른 분들의 의견이 궁금합니다!
> Feature/#398 하드 코딩된 테스트 코드를 수정

- src/main/java/com/keeper/homepage/domain/library/application/BookService.java
- src/main/java/com/keeper/homepage/domain/library/dao/BookBorrowLogRepository.java
- src/main/java/com/keeper/homepage/global/error/ErrorCode.java
- src/test/java/com/keeper/homepage/domain/library/application/BookServiceTest.java
https://github.com/KEEPER31337/Homepage-Back-R2/issues/396
- 사서님 요구사항에 맞추어서 기본적인 부분들 반영하였습니다.
```
<대출규정 관련건>
최대 대출 권수는 2권으로 한다.
반납일 포함 3일이 경과된 후에 재대출이 가능하다.
```
였으며 규정 반영에 따라서 테스트코드도 요구사항에 맞추어 변경해주었습니다.
이 외에 사서님이 요구하신 기존에 없는 새롭게 추가되는 기능들은 새로운 이슈로 파서 프론트엔드 한 분과 디자이너와 함께 논의하며 개발하면 좋을 것 같습니다.
- 더 좋은 네이밍 있으면 추천해주셨으면 좋겠습니다.
- `book_borrow_info`테이블에 반납 완료 날짜가 없어서 `book_borrow_log`에서 가져오는 로직을 수행했습니다.
- 해당 쿼리는 `BookBorrowLogRepository`안에 있는데 페이지네이션한 쿼리들 안에 있어서 그런지 뭔가 있으면 안될 자리에 있다는 느낌이 드네요. 그러나 마땅히 괜찮은 위치를 찾지 못해서 일단 여기 뒀습니다.
> Feature/#396 도서 관리 기능을 사서의 요구사항에 맞게 변경

- src/main/java/com/keeper/homepage/domain/seminar/api/SeminarAttendanceController.java
- src/test/java/com/keeper/homepage/domain/seminar/api/SeminarAttendanceControllerTest.java
close: #394
기존의 세미나 출석 정보 조회는 생성된 회원 순으로 정렬됩니다.
세미나 출석 정보 조회를 기수 순으로 정렬하고, 동일 기수 내라면 이름 순으로 정렬하는 코드를 추가했습니다.
정렬 Controller 코드 단에서 하는 걸로 괜찮을까요?
테스트 코드를 따로 작성 안하고 기존 테스트 코드만 살짝 수정했습니다. 기수 순으로도 잘 정렬 되는지 테스트 추가하고 싶었는데 Generation을 설정하려면 엔티티 코드를 건드려야 할거 같아서 일단 뺐습니다... (기수순으로도 정렬 되는거 확인은 했습니다!)
추가적인 테스트 코드 필요할 거 같으면 말씀해주세요~!
> Feature/세미나 출석 정보 조회시 기수와 이름 정렬을 추가한다.

- src/test/java/com/keeper/homepage/domain/auth/api/test/AuthTestControllerTest.java
https://github.com/KEEPER31337/Homepage-Back-R2/issues/398
https://github.com/KEEPER31337/Homepage-Back-R2/pull/402
동적으로 application.yml에 있는 key 값을 토대로 만료된 accessToken을 만들도록 했습니다.
> Feature/#398 하드코딩된 테스트 코드 수정

- src/main/java/com/keeper/homepage/global/util/aop/ApiStatisticAop.java
> close: #412
스케줄러와 AOP를 함께 사용했을 때 스케줄러가 도는 시점에 아래 에러가 뜸.
<details>
<summary>error 문구</summary>
<div markdown="1">
```
2024-05-03T15:01:11.019+09:00 ERROR 64836 --- [   scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task
org.springframework.beans.factory.support.ScopeNotActiveException: Error creating bean with name 'scopedTarget.apiStatistic': Scope 'request' is not active for the current thread; consider defining a scoped proxy for this bean if you intend to refer to it from a singleton
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:374) ~[spring-beans-6.0.4.jar:6.0.4]
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) …
```
> #412 스프링 스케줄러 & AOP 충돌 해결

- .github/workflows/check_pull_request.yml
- .github/workflows/pull_request_test.yml
https://github.com/KEEPER31337/Homepage-Back-R2/issues/422
코드를 가져온 후 gradle build를 통해서 작성한 테스트 코드가 문제없는지 확인합니다.
> Feature/#422 PR에 CI 도입

- src/docs/asciidoc/post/post.adoc
- src/main/java/com/keeper/homepage/domain/file/application/FileService.java
- src/main/java/com/keeper/homepage/domain/file/dao/FileRepository.java
- src/main/java/com/keeper/homepage/domain/file/entity/FileEntity.java
- src/main/java/com/keeper/homepage/domain/post/api/PostController.java
- src/main/java/com/keeper/homepage/domain/post/application/PostService.java
- src/main/java/com/keeper/homepage/domain/post/dto/response/FileForContentResponse.java
- src/main/java/com/keeper/homepage/global/util/file/server/FileServerUtil.java
- src/test/java/com/keeper/homepage/domain/post/api/PostApiTestHelper.java
- src/test/java/com/keeper/homepage/domain/post/api/PostControllerTest.java
> close: #109
게시글 본문용 이미지 업로드/다운로드 기능 추가
이미지 다운로드는 file hash를 이용하도록 했습니다.
- mysql에 추가한 컬럼과 sql 쿼리는 아래와 같습니다
```sql
ALTER TABLE file ADD file_uuid VARCHAR(50) NULL;
ALTER TABLE file ADD UNIQUE INDEX file_uuid_index (file_uuid);
```
> feat: 게시글 본문 이미지 업로드/다운로드 기능 추가

- src/main/java/com/keeper/homepage/domain/game/application/BaseballService.kt
- src/main/java/com/keeper/homepage/global/error/ErrorCode.java
- src/test/java/com/keeper/homepage/domain/game/api/GameControllerTest.kt
> close: #
- 야구 게임 최대 베팅 금액을 5000에서 3000으로 수정했습니다 .
- 1000과 3000사이 베팅 포인트를 벗어나는 경우에 대한 에러 코드를 추가했습니다.
- earnable point 를 기존의 *2배로 변경하였습니다 .
- 테스트를 돌리면 한 군데에서 아래 사진과 같은 test failed가 뜨는데 제가 야구 게임 코드를 다 파악하지 못해서 보시고 알려주시면 감사하겠습니다!
> feat: 야구게임 베팅가능 금액 변경
